Atractorrr/Attraction-Server

src/main/java/run/attraction/api/v1/introduction/Article.java
src/main/java/run/attraction/api/v1/introduction/Category.java
src/main/java/run/attraction/api/v1/introduction/Newsletter.java
src/main/java/run/attraction/api/v1/introduction/UploadDays.java
src/test/java/run/attraction/api/v1/introduction/CategoryTest.java
src/test/java/run/attraction/api/v1/introduction/UploadDaysTest.java

<br/>
- ATR-51
<br/>
- 뉴스레터 Entity 생성
<br/>
-
<br/>

Feature/ATR-51 뉴스레터 entity 생성

---

src/main/java/run/attraction/api/v1/introduction/controller/IntroductionController.java
src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
src/main/java/run/attraction/api/v1/introduction/exception/ErrorMessages.java
src/main/java/run/attraction/api/v1/introduction/exception/IntroductionExceptionHandler.java
src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java
src/test/java/run/attraction/api/v1/introduction/controller/IntroductionControllerTest.java
src/test/java/run/attraction/api/v1/introduction/service/IntroductionServiceTest.java

<br/>
- ATR-64
<br/>
- 이전 articles get API 구현
- 특정 뉴스레터의 이전 아티클들을 return 함
- 예외 처리 구현
- api를 사용하면서 발생할 수 있는 예외 처리 구현
<br/>
-
<br/>

[ATR-64] feat: 이전 articles get api

---

src/main/java/run/attraction/api/v1/introduction/controller/IntroductionController.java
src/main/java/run/attraction/api/v1/introduction/dto/response/NewslettersByCategoryResponse.java
src/main/java/run/attraction/api/v1/introduction/exception/ErrorMessages.java
src/main/java/run/attraction/api/v1/introduction/repository/NewsletterRepository.java
src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java
src/test/java/run/attraction/api/v1/introduction/controller/IntroductionControllerTest.java
src/test/java/run/attraction/api/v1/introduction/service/IntroductionServiceTest.java

<br/>
- ATR-66
<br/>
- 연관된 뉴스레터 get API 구현
- 현재는 데이터 부족으로 카테고리를 기준으로 랜덤하게 연관된 뉴스레터를 가져옴
- 테스트 코드 서비스단만 구현
<br/>
- 테스트 코드 controller 부분 추가해야함
- 예외처리 더 생각해서 촘촘하게 구현해야함
-
<br/>

[ATR-66] feat: 관련된 뉴스레터 get api

---

src/main/java/run/attraction/api/v1/user/Interest.java
src/main/java/run/attraction/api/v1/user/Occupation.java
src/main/java/run/attraction/api/v1/user/User.java
src/main/java/run/attraction/api/v1/user/init/Userinit.java
src/main/java/run/attraction/api/v1/user/repository/UserRepository.java
src/main/java/run/attraction/api/v1/user/service/UserDetailsServiceForSecurity.java
src/main/java/run/attraction/api/v1/user/service/UserService.java
src/main/java/run/attraction/api/v1/user/service/UserServiceImpl.java

<br/>
- https://attractorr.atlassian.net/browse/ATR-102?atlOrigin=eyJpIjoiZTg2ZTlhNWEzNDllNDI4NjhhZDNiZDdjNmI0NDc2YTkiLCJwIjoiaiJ9
<br/>
-
<br/>
-
<br/>

[ATR-102] feat: User Entity Id 변경

---

src/main/java/run/attraction/api/v1/archive/Article.java
src/main/java/run/attraction/api/v1/introduction/Newsletter.java

<br/>
- ATR-106
<br/>
- 엔티티 수정
- article entity
- newsletter entity
<br/>
-
<br/>

[ATR-106] feat: modify entity

---

src/main/java/run/attraction/api/v1/archive/Article.java
src/main/java/run/attraction/api/v1/introduction/Newsletter.java

- [] Bugfix
<br/>
- ATR 105
<br/>
-
<br/>
-
<br/>

[ATR-106] feat: entity 수정 (#18)

---

src/main/java/run/attraction/api/v1/auth/config/properties/GoogleLoginProperties.java
src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
src/main/java/run/attraction/api/v1/auth/provider/google/GoogleOAuthService.java
src/main/java/run/attraction/api/v1/auth/service/AuthService.java
src/main/java/run/attraction/api/v1/auth/service/dto/UserTokenDto.java
src/main/java/run/attraction/api/v1/auth/service/dto/join/JoinRequestDto.java
src/main/java/run/attraction/api/v1/auth/service/dto/login/FirstLoginResponseDto.java
src/main/java/run/attraction/api/v1/auth/service/helper/AuthProviderAndTokenHelper.java
src/main/java/run/attraction/api/v1/auth/service/helper/JoinHelper.java
src/main/java/run/attraction/api/v1/auth/token/RefreshToken.java
src/main/java/run/attraction/api/v1/auth/token/jwt/JwtServiceImpl.java
src/main/java/run/attraction/api/v1/mypage/controller/MyPageController.java
src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
src/main/java/run/attraction/api/v1/mypage/service/dto/UserDetaiilDto.java
src/main/java/run/attraction/api/v1/mypage/service/user/MyPageUserSeriveImpl.java
src/main/java/run/attraction/api/v1/mypage/service/user/MyPageUserService.java
src/main/java/run/attraction/api/v1/user/User.java
src/main/java/run/attraction/api/v1/user/init/Userinit.java
src/main/java/run/attraction/api/v1/user/service/UserServiceImpl.java

<br/>
- [ATR-102] chore: User Entity 필드 이름 변경
(https://github.com/Atractorrr/Attraction-Server/commit/776320ac215d0d1a19b13fa1e16b72d66f445bec)
<br/>
-
<br/>
-
<br/>
[ATR-102]: https://attractorr.atlassian.net/browse/ATR-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-102] chore: User Entity 필드 이름 변경

---

src/main/java/run/attraction/api/v1/archive/InBox.java
src/main/java/run/attraction/api/v1/archive/ReadBox.java
src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
src/main/java/run/attraction/api/v1/archive/dto/ArticleDTO.java
src/main/java/run/attraction/api/v1/archive/dto/NewsletterDTO.java
src/main/java/run/attraction/api/v1/archive/dto/request/UserArticlesRequest.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/resources/data.sql

[ATR - 122] feat: modify code

---

src/main/java/run/attraction/api/v1/archive/repository/ReadBoxRepository.java
src/main/java/run/attraction/api/v1/mypage/controller/MyPageController.java
src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
src/main/java/run/attraction/api/v1/mypage/service/dto/UserDetailDto.java
src/main/java/run/attraction/api/v1/mypage/service/dto/UserDetailsResponseDto.java
src/main/java/run/attraction/api/v1/mypage/service/user/MyPageUserSeriveImpl.java
src/main/java/run/attraction/api/v1/mypage/service/user/MyPageUserService.java

[ATR-6] feat: 마이페이지 유저정보 API 수정 및 ReadBox Repository 생성

---

src/main/java/run/attraction/api/v1/archive/InBox.java
src/main/java/run/attraction/api/v1/archive/ReadBox.java
src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
src/main/java/run/attraction/api/v1/archive/dto/ArticleDTO.java
src/main/java/run/attraction/api/v1/archive/dto/NewsletterDTO.java
src/main/java/run/attraction/api/v1/archive/dto/request/UserArticlesRequest.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/resources/data.sql

<br/>
- ATR-122
<br/>
-
<br/>
-
<br/>

[ATR-122] feat: modify code

---

src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
src/main/java/run/attraction/api/v1/archive/repository/ReadBoxRepository.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java

- updateUserArticlePercentage 구현 -
<br/>
- ATR-128
<br/>
-
<br/>
-
<br/>

[ATR - 128] feat: 유저 아티클 퍼센테지 업데이트 기능 구현

---

src/main/java/run/attraction/api/v1/mypage/controller/MyPageController.java
src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
src/main/java/run/attraction/api/v1/mypage/service/calendar/MypageCalendarService.java
src/main/java/run/attraction/api/v1/mypage/service/calendar/MypageCalendarServiceImpl.java
src/main/java/run/attraction/api/v1/mypage/service/dto/calendar/CalendarDay.java
src/main/java/run/attraction/api/v1/mypage/service/dto/calendar/CalendarResponseDto.java
src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UserDetailDto.java
src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UserDetailsResponseDto.java
src/main/java/run/attraction/api/v1/mypage/service/user/MyPageUserService.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
src/main/resources/data.sql

<br/>
- [ATR-91](https://attractorr.atlassian.net/browse/ATR-91?atlOrigin=eyJpIjoiYTU2ZmU3ZjJhNDYxNDllOTkyNDQyNDc0NTUwZTc4NWUiLCJwIjoiaiJ9) :  마이페이지 잔디밭 API
<br/>
-
<br/>
-
<br/>
[ATR-91]: https://attractorr.atlassian.net/browse/ATR-91?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-91] feature: 마이페이지 잔디밭 API

---

src/test/java/run/attraction/api/v1/mypage/service/calendar/MypageCalendarServiceTest.java

<br/>
- [ATR-91](https://attractorr.atlassian.net/browse/ATR-91?atlOrigin=eyJpIjoiYTU2ZmU3ZjJhNDYxNDllOTkyNDQyNDc0NTUwZTc4NWUiLCJwIjoiaiJ9) :  마이페이지 잔디밭 API
<br/>
-
<br/>
-
<br/>
[ATR-91]: https://attractorr.atlassian.net/browse/ATR-91?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-91] feat: 마이페이지 잔디밭 API 테스트코드

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/archive/repository/ReadBoxRepository.java
src/main/java/run/attraction/api/v1/introduction/repository/NewsletterRepository.java
src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleService.java
src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java
src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/MypageArticle.java
src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/RecentArticlesResponseDto.java
src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/UserArticleDetail.java
src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/UserArticleImg.java
src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/UserReadBoxDetail.java
src/main/resources/data.sql

<br/>
- [ATR-92](https://attractorr.atlassian.net/browse/ATR-92?atlOrigin=eyJpIjoiYzFhNmYzNmQzOTk5NDMwNGIwNzYxNmMwNjYxMDI3MjAiLCJwIjoiaiJ9) : 마이페이지 - 최근 읽은 아티클 API
<br/>
-
<br/>
-
<br/>
[ATR-92]: https://attractorr.atlassian.net/browse/ATR-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-92] feat: 최근 읽은 아티클 API

---

src/main/java/run/attraction/AttractionApplication.java
src/main/java/run/attraction/api/v1/archive/AdminArticle.java
src/main/java/run/attraction/api/v1/archive/Article.java
src/main/java/run/attraction/api/v1/archive/AuditableEntity.java
src/main/java/run/attraction/api/v1/archive/ReadBox.java
src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/introduction/exception/ErrorMessages.java

<br/>
- ATR-158
<br/>
-
<br/>
-
<br/>

[ATR-158] refactor: user article percentage

---

src/main/java/run/attraction/AttractionApplication.java
src/main/java/run/attraction/api/v1/archive/AdminArticle.java
src/main/java/run/attraction/api/v1/archive/Article.java
src/main/java/run/attraction/api/v1/archive/AuditableEntity.java
src/main/java/run/attraction/api/v1/archive/ReadBox.java
src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/introduction/exception/ErrorMessages.java
src/test/java/run/attraction/api/v1/introduction/service/IntroductionServiceTest.java

<br/>
- ATR 158
<br/>
-
<br/>
-
<br/>

[ATR - 158] refactor: user article percentage

---

src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java

<br/>
-  [ATR-92](https://attractorr.atlassian.net/browse/ATR-92?atlOrigin=eyJpIjoiNDJkODg0NGUzYmQ1NGIyMzgwYzM1OGY1MjI0YjhjNTMiLCJwIjoiaiJ9) 최근 읽은 아티클 API
<br/>
- ReadBox의 readDate : readPercentage가 100% 되었을때 시간
- ReadBox의 updateAt : 최근에 읽은 아티클 날짜
- readDate에서 updateAt 날짜로 최근 읽은 아티클의 날짜 추출
<br/>
-
<br/>
[ATR-92]: https://attractorr.atlassian.net/browse/ATR-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-92] feat: 최근 읽은 아티클 API 수정

---

src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateProfileImgRequestDto.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserService.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
src/main/java/run/attraction/api/v1/user/User.java
src/test/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceTest.java

<br/>
- [ATR-165](https://attractorr.atlassian.net/browse/ATR-165?atlOrigin=eyJpIjoiZTJiMzU5YjJlYjc3NDVkZmEzNmY0NzE3NmMxZTkxNWIiLCJwIjoiaiJ9) : 프로필 이미지 수정
<br/>
- 마이페이지에서 발생하는 프로필 이미지 변경 API 작성 및 테스트 코드 작성
- Post Man & 테스트코드 통과
<br/>
-
<br/>
[ATR-165]: https://attractorr.atlassian.net/browse/ATR-165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-165] feat: 프로필 이미지 수정 API

---

src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateBackgroundImgRequestDto.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserService.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
src/test/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceTest.java

<br/>
- (ATR-166)[https://attractorr.atlassian.net/browse/ATR-166?atlOrigin=eyJpIjoiNzUzMTgzOWMxYmFjNGM3ZmEyNDZkMzUzZWEwODUxZDQiLCJwIjoiaiJ9] : 마이페이지 - 배경 이미지 수정
<br/>
- 마이페이지에서 발생하는 배경 이미지 변경 API 작성 및 테스트 코드 작성
- Post Man & 테스트코드 통과
<br/>
-
<br/>

[ATR-166] feat: 마이페이지 배경 이미지 수정 API

---

src/main/java/run/attraction/api/v1/archive/ReadBox.java
src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java

<br/>
- ATR-164
<br/>
- 기존 유저 아티클 퍼센테이지 업데이트시 해당 아티클에 readBox가 존재하지 않을시 생성 후 업데이트
- 메서드명 변경 updateUserArticlePercentage - saveUserArticleProgress
- readBox 생성자 추가
- percentage 기본값 추가 (기본값 0)
<br/>
-
<br/>

[ATR - 164] feat: percentage 업데이트 시 readBox가 존재하지 않으면 생성 

---

src/main/java/run/attraction/api/v1/archive/Subscribe.java
src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
src/main/java/run/attraction/api/v1/archive/repository/SubscribeRepository.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java

<br/>
- ATR-167
<br/>
- addNewsletter 메서드 추가
- subscribe entity 추가
- subscribe repository 추가
<br/>
-
<br/>

[ATR-167] feat: 유저가 뉴스레터 구독하면 구독함에 추가

---

src/main/resources/data.sql

<br/>
- 
<br/>
-
<br/>
-
<br/>

[ATR-90] style: data.sql 수정

---

build.gradle
src/main/java/run/attraction/api/v1/auth/config/AuthProviderConfig.java
src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
src/main/java/run/attraction/api/v1/auth/controller/AuthTestController.java
src/main/java/run/attraction/api/v1/auth/provider/AuthProvider.java
src/main/java/run/attraction/api/v1/auth/provider/google/GoogleOAuthService.java
src/main/java/run/attraction/api/v1/auth/provider/oauth/OAuthToken.java
src/main/java/run/attraction/api/v1/auth/service/dto/login/LoginResponseDto.java
src/main/java/run/attraction/api/v1/auth/token/GoogleRefreshToken.java
src/main/java/run/attraction/api/v1/auth/token/repository/GoogleRefreshTokenRepository.java
src/main/java/run/attraction/api/v1/user/Occupation.java
src/main/java/run/attraction/api/v1/user/User.java
src/main/resources/data.sql

<br/>
-  [ATR-170 ](https://attractorr.atlassian.net/browse/ATR-170?atlOrigin=eyJpIjoiYjA0ODhjOGRhYTgyNDdiOTgwZWMyNzk3ZmRiZDAwNGIiLCJwIjoiaiJ9)
<br/>
- gmail 위임 완료 후, 유저의 이메일을 읽을때 구글 RefreshToken이 필요
- 이를 위한 GoogleRefreshToken 엔티티 생성
- 회원가입때 구글 API에서 보내주는 refreshToken 저장
<br/>
-
<br/>

[ATR-170] feat: google refresh token 추가

---

src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java
src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateBackgroundImgRequestDto.java
src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateProfileImgRequestDto.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserService.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
src/main/java/run/attraction/api/v1/user/User.java
src/main/resources/data.sql
src/test/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceTest.java

<br/>
- [ATR-92](https://attractorr.atlassian.net/browse/ATR-92?atlOrigin=eyJpIjoiYWU3YzFjZjY4Yzc0NDZkZjgyNmFkNjE1ZDMwOWUzMzIiLCJwIjoiaiJ9)
- [ATR-165](https://attractorr.atlassian.net/browse/ATR-165?atlOrigin=eyJpIjoiZjc2YWZiMjEwNGI3NDQ5MGI0Nzk5ZjYyZWNmZWQ5MzciLCJwIjoiaiJ9)
- [ATR-166](https://attractorr.atlassian.net/browse/ATR-166?atlOrigin=eyJpIjoiYTcxODNhMjQwZWRiNGI0OWJiMjA0ZDY2YWQzMDM0MGMiLCJwIjoiaiJ9) 
<br/>
- 최근 읽은 아티클은 updateAt 데이터가 필요하여, readDate -> updateAt으로 변경
( ReadBox의 readDate : readPercentage가 100% 되었을때 시간 )
( ReadBox의 updateAt : 최근에 읽은 아티클 날짜 )
- 마이페이지 프로필 이미지 /  배경이미지 API 추가
<br/>
-
<br/>
[ATR-92]: https://attractorr.atlassian.net/browse/ATR-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATR-165]: …

[ATR-6] feat: 마이페이지 API 추가

---

src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateUserDetailDto.java
src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateUserDetailRequestDto.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserService.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
src/main/java/run/attraction/api/v1/user/User.java
src/test/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceTest.java

<br/>
-[ATR-134](https://attractorr.atlassian.net/browse/ATR-134?atlOrigin=eyJpIjoiNmU0OThhNjZmMzYzNDdlYzhhMzEwZmQ5MDY4YjIyYjAiLCJwIjoiaiJ9)
<br/>
- 마이페이지 개인 설정 
- 1.닉네임 중복 체크 API
- 2.개인설정 반영 API
- 개인 설정 가능 목록
- 1. 닉네임
- 2. 만료일
- 3. 관심사
- 4. 직업군
<br/>
-
<br/>
[ATR-134]: https://attractorr.atlassian.net/browse/ATR-134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-134] feat: 마이페이지 개인 설정

---

src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UserDetailDto.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
src/main/resources/data.sql

<br/>
- [ATR-90](https://attractorr.atlassian.net/browse/ATR-90?atlOrigin=eyJpIjoiZGJlYjY0MjlmMjEzNGVkYjk0NmFhOTZkZTg0YzhiYzYiLCJwIjoiaiJ9)
<br/>
- 반환값에 직업군(Occupation), 유효기간(userExpiration) 같이 반환
<br/>
-
<br/>
[ATR-90]: https://attractorr.atlassian.net/browse/ATR-90?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-90] feat: 마이페이지 유저 정보 요청 API 수정

---

src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
src/main/java/run/attraction/api/v1/mypage/service/archive/newsletter/MypageNewsletterService.java
src/main/java/run/attraction/api/v1/mypage/service/archive/newsletter/MypageNewsletterServiceImpl.java
src/main/java/run/attraction/api/v1/mypage/service/dto/archive/newsletter/MypageNewsletterDetail.java
src/main/java/run/attraction/api/v1/mypage/service/dto/archive/newsletter/SubscribeResponseDto.java
src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateUserDetailDto.java
src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateUserDetailRequestDto.java
src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UserDetailDto.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserService.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
src/main/java/run/attraction/api/v1/user/User.java
src/main/resources/data.sql
src/test/java/run/attraction/api/v1/mypage/service/archive/MypageNewsletterSerivceTest.java
src/test/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceTest.java

<br/>
- [ATR-93](https://attractorr.atlassian.net/browse/ATR-93?atlOrigin=eyJpIjoiOTE3Y2U0OTY1ZGFhNDQ1NzhiMjRlZjc4NWNjMWNkNWIiLCJwIjoiaiJ9)
- [ATR-134](https://attractorr.atlassian.net/browse/ATR-134?atlOrigin=eyJpIjoiM2UzZDI1MDE1MGYyNDU0Mjk3OTkwNjk2ZDk0MDc2ZTciLCJwIjoiaiJ9)
- [ATR-90](https://attractorr.atlassian.net/browse/ATR-90?atlOrigin=eyJpIjoiNWNiODQyZjA2MWRlNDNjYjg0ODQ0ZGFmMGNkOWVhMzYiLCJwIjoiaiJ9)
<br/>
- 마이페이지 구독리스트 API 추가
- 마이페이지 개인설정 API 추가
- 개인 설정 수정 가능 항목
- 1. 닉네임
- 2. 만료일
- 3. 관심사
- 4. 직업군
- 마이페이지 유저 정보 유청 API 수정 (반환값에 직업군(Occupation), 유효기간(userExpiration) 같이 반환)
<br/>
-
<br/>
[ATR-93]: https://attractorr.atlassian.net/browse/ATR-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATR-134]: …

[ATR-6] feat: 마이페이지 API 추가 및 수정

---

src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
src/main/java/run/attraction/api/v1/auth/provider/AuthProvider.java
src/main/java/run/attraction/api/v1/auth/service/dto/UserTokenDto.java
src/main/java/run/attraction/api/v1/auth/service/dto/login/LoginResponseDto.java
src/main/java/run/attraction/api/v1/auth/service/helper/AuthProviderAndTokenHelper.java
src/main/java/run/attraction/api/v1/auth/token/GoogleRefreshToken.java
src/main/java/run/attraction/api/v1/auth/token/repository/GoogleRefreshTokenRepository.java

<br/>
- [ATR-177](https://attractorr.atlassian.net/browse/ATR-177?atlOrigin=eyJpIjoiMWRiZTg5ZmIyMGQwNDFjMGIxYzc0NDBlNWJhNmRjZWEiLCJwIjoiaiJ9)
<br/>
- 반환값으로 GoogleRefreshToken의 shouldReissueToken 추가
<br/>
-
<br/>
[ATR-177]: https://attractorr.atlassian.net/browse/ATR-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-177] feat: 로그인 반환값 변경

---

src/main/java/run/attraction/api/v1/home/controller/HomeController.java
src/main/java/run/attraction/api/v1/home/service/HomeService.java
src/main/java/run/attraction/api/v1/home/service/dto/categories/CategoriesResponseDto.java
src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterService.java
src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterServiceImpl.java
src/test/java/run/attraction/api/v1/home/service/HomeServiceTest.java

<br/>
- [ATR-162](https://attractorr.atlassian.net/browse/ATR-162?atlOrigin=eyJpIjoiNzRjOGQyMTczYWY1NDU5M2I1NTlkOWYxODExNjJmOTQiLCJwIjoiaiJ9)
<br/>
- 메인페이지의 트렌드한 뉴스레터에서 사용할 카테고리를 반환하는 API
- 전달받은 email이 없다면 비회원으로 인식하여 default 카테고리 순서대로 반환
- email 값을 전달받았다면, 유저의 관심사 카테고리가 앞으로 나오도록 카테고리 정렬
<br/>
-
<br/>
[ATR-162]: https://attractorr.atlassian.net/browse/ATR-162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-162] feat: 트렌디한 뉴스레터 카테고리 API

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/home/controller/HomeController.java
src/main/java/run/attraction/api/v1/home/service/HomeService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
src/main/java/run/attraction/api/v1/home/service/dto/article/ArticleDetailDto.java
src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticlesResponseDto.java
src/main/resources/data.sql

<br/>
- [ATR-160](https://attractorr.atlassian.net/browse/ATR-160?atlOrigin=eyJpIjoiZDU2OTQ0ODhiMWI1NGFlNGE4NzZhYThjYjk4NmY1NDkiLCJwIjoiaiJ9)
<br/>
- 메인페이지 최근 받은 뉴스레터 API
- email을 전달받으면 최근 7일간 받은 뉴스레터를 반환
<br/>
-
<br/>
[ATR-160]: https://attractorr.atlassian.net/browse/ATR-160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-160] feat: 메인페이지 최근 받은 뉴스레터 API

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/archive/repository/SubscribeRepository.java
src/main/java/run/attraction/api/v1/home/controller/HomeController.java
src/main/java/run/attraction/api/v1/home/service/HomeService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
src/main/java/run/attraction/api/v1/home/service/dto/article/ArticleDetailDto.java
src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticlesResponseDto.java
src/main/java/run/attraction/api/v1/home/service/dto/categories/CategoriesResponseDto.java
src/main/java/run/attraction/api/v1/home/service/dto/newsletter/NewsletterDetailDto.java
src/main/java/run/attraction/api/v1/home/service/dto/newsletter/NewslettersResponseDto.java
src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterService.java
src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterServiceImpl.java
src/main/java/run/attraction/api/v1/introduction/Newsletter.java
src/main/java/run/attraction/api/v1/introduction/repository/NewsletterRepository.java
src/main/resources/data.sql
src/test/java/run/attraction/api/v1/home/service/HomeServiceTest.java

<br/>
- [ATR-162](https://attractorr.atlassian.net/browse/ATR-162?atlOrigin=eyJpIjoiNGRmYmUyZGZjMDA0NDQyMTkxZTEyMGYyZjU4NGI4ZGIiLCJwIjoiaiJ9)
- [ATR-161](https://attractorr.atlassian.net/browse/ATR-161?atlOrigin=eyJpIjoiN2EwN2EwOTViZDBhNDU3ZmI5ZTQ0Y2Y0YzA5MzE4MzciLCJwIjoiaiJ9)
- [ATR-160](https://attractorr.atlassian.net/browse/ATR-160?atlOrigin=eyJpIjoiMzY0MjQzZTM0OGRkNDQ5ODhkN2Q3MTI4ZWUwY2U1YmYiLCJwIjoiaiJ9)
<br/>
-  트렌디한 뉴스레터 카테고리 API
-  트렌디한 뉴스레터 API
-  최근 받은 아티클 API
<br/>
-
<br/>
[ATR-162]: https://attractorr.atlassian.net/browse/ATR-162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATR-161]: https://attractorr.atlassian.net/browse/ATR-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

[ATR-24] feat: 메인페이지 API

---

Dockerfile

chore: 공백 추가

---

.gitignore
src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
src/main/java/run/attraction/api/v1/archive/dto/NewsletterEmail.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/auth/provider/AuthProvider.java
src/main/java/run/attraction/api/v1/auth/token/dto/UserGmailToken.java
src/main/java/run/attraction/api/v1/auth/token/repository/GoogleRefreshTokenRepository.java
src/main/java/run/attraction/api/v1/auth/token/service/GoogleTokenService.java
src/main/java/run/attraction/api/v1/gmail/GmailApiAccessException.java
src/main/java/run/attraction/api/v1/gmail/GmailClient.java
src/main/java/run/attraction/api/v1/gmail/GoogleClientSecretsNotLoadedException.java

<br/>
- ATR-195
<br/>
- 사용자가 뉴스레터를 구독하면 해당 뉴스레터를 Gmail 라벨 처리해주고 라벨함에만 저장될 수 있도록 Filter 처리를 합니다.
<br/>
-
<br/>

[ATR-195] feat: 뉴스레터 구독시 사용자 메일함 처리

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java
src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/UserArticleDetail.java
src/main/resources/data.sql

<br/>
- ATR-92
<br/>
- date: 최근 읽은 날짜
- receivedAt: 아티클 받은 날짜
- 
<br/>
-
<br/>

[ATR-92] feat: 최근 읽은 아티클 API 반환값 수정

---

src/main/java/run/attraction/api/v1/home/service/dto/newsletter/NewslettersResponseDto.java

style: responseDto 이름변경

---

src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
src/main/java/run/attraction/api/v1/auth/provider/AuthProvider.java
src/main/java/run/attraction/api/v1/auth/provider/google/GoogleOAuthService.java
src/main/java/run/attraction/api/v1/auth/service/AuthService.java
src/main/java/run/attraction/api/v1/auth/service/helper/AuthProviderAndTokenHelper.java
src/main/java/run/attraction/api/v1/auth/token/CookieTokenSetter.java
src/main/java/run/attraction/api/v1/auth/token/jwt/JwtServiceImpl.java
src/main/java/run/attraction/api/v1/user/service/UserServiceImpl.java

style: jwt 생성 log 처리

---

src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
src/main/java/run/attraction/api/v1/auth/service/dto/join/CheckDuplicationRequsetDto.java

style: 중복체크 request 변경

---

src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
src/main/java/run/attraction/api/v1/auth/service/dto/join/CheckDuplicationResponseDto.java

style: 중복체크 response  변경

---

src/main/java/run/attraction/api/v1/auth/service/AuthService.java
src/main/java/run/attraction/api/v1/auth/service/dto/join/JoinRequestDto.java
src/main/java/run/attraction/api/v1/auth/service/helper/JoinHelper.java
src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateUserDetailDto.java
src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateUserDetailRequestDto.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserService.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
src/main/java/run/attraction/api/v1/user/User.java
src/main/java/run/attraction/api/v1/user/repository/UserRepository.java

- [] Feature
<br/>
-
<br/>
-
<br/>
-
<br/>

style: 필드 이름 변경

---

src/main/java/run/attraction/api/v1/user/User.java

style: toList -> collect(Collectors.toList())

---

src/main/java/run/attraction/api/v1/archive/Subscribe.java
src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
src/main/java/run/attraction/api/v1/archive/repository/SubscribeRepository.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/introduction/repository/NewsletterRepository.java
src/main/java/run/attraction/api/v1/mypage/service/archive/newsletter/MypageNewsletterServiceImpl.java
src/main/resources/data.sql

<br/>
- [ATR-207](https://attractorr.atlassian.net/browse/ATR-207?atlOrigin=eyJpIjoiMTdiNDFlNzJkOGViNDU5OGFkMzAzZDAzYzRhZGZiMWUiLCJwIjoiaiJ9)
<br/>
[[ATR-207] feat: newsletter 연관관계 제거](https://github.com/Atractorrr/Attraction-Server/commit/1763f92d2cc0b1769221617a3a5562ff7dc8c808) 
[[ATR-207] feat: subscribe entity 변경으로 인하여 수정](https://github.com/Atractorrr/Attraction-Server/commit/a8cddaa521485c8a38e38ce3aab69d5f1c91ec31)
[[ATR-207] feat: 유저의 구독리스트를 전부 가져오는 get 메서드 생성](https://github.com/Atractorrr/Attraction-Server/commit/7e316d36d3e7482701413ebdca03e961abad987e) 
<br/>
-
<br/>
[ATR-207]: https://attractorr.atlassian.net/browse/ATR-207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATR-207]: …

[ATR-207] : feat: subscribe 엔티티 수정

---

src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterServiceImpl.java
src/main/java/run/attraction/api/v1/user/init/Userinit.java

style: 글자 수정 및 UserInit 주석처리

---

src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterServiceImpl.java

<br/>
- [ATR-221](https://attractorr.atlassian.net/browse/ATR-221?atlOrigin=eyJpIjoiZGI3N2VkZGQ2Y2E3NGE3ZmE0NTQ1YzBhMGEyNjBjNGEiLCJwIjoiaiJ9)
<br/>
-
<br/>
-
<br/>
[ATR-221]: https://attractorr.atlassian.net/browse/ATR-221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-221] feat: findAllByIds -> findNewslettersByNewsletterIds로 변경

---

src/main/java/run/attraction/api/v1/archive/AuditableEntity.java
src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java

<br/>
- [ATR-222](https://attractorr.atlassian.net/browse/ATR-222?atlOrigin=eyJpIjoiYmY5MjY1Y2Y3ZWFhNDBlYjk0MTI2OTUxOTA1YjJhOWUiLCJwIjoiaiJ9)
<br/>
- [[ATR-222] style: AuditableEntity 변수명 변경](https://github.com/Atractorrr/Attraction-Server/commit/1b49a0541fbdcdf75aa3f32d108a724beb3116c0) 
- createAt -> createdAt
- updateAt -> modifiedAt
<br/>
-
<br/>
[ATR-222]: https://attractorr.atlassian.net/browse/ATR-222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATR-222]: https://attractorr.atlassian.net/browse/ATR-222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-222] style: AuditableEntity 변수명 변경

---

src/main/java/run/attraction/api/v1/archive/AuditableEntity.java
src/main/java/run/attraction/api/v1/auth/provider/google/GoogleOAuthService.java
src/main/java/run/attraction/api/v1/auth/service/helper/JoinHelper.java
src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java
src/main/java/run/attraction/api/v1/user/User.java
src/main/java/run/attraction/api/v1/user/UserDetail.java

<br/>
- [ATR-222](https://attractorr.atlassian.net/browse/ATR-222?atlOrigin=eyJpIjoiYjk4NGQ3MmM5YjE1NDQ5MTk3MmRiYzdhMWViZDYyNTEiLCJwIjoiaiJ9)
- [ATR-223](https://attractorr.atlassian.net/browse/ATR-223?atlOrigin=eyJpIjoiMTRhMjRlNDEwZjg1NGJjYzk2MDcwYWJkNjA3NWNjNjUiLCJwIjoiaiJ9)
<br/>
-
<br/>
-
<br/>
[ATR-222]: https://attractorr.atlassian.net/browse/ATR-222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATR-223]: https://attractorr.atlassian.net/browse/ATR-223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: AuditableEntity 수정 및 적용

---

src/main/java/run/attraction/api/v1/home/controller/HomeController.java
src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
src/main/java/run/attraction/api/v1/mypage/service/dto/MessageResponse.java

<br/>
- [ATR-224](https://attractorr.atlassian.net/browse/ATR-224?atlOrigin=eyJpIjoiNTBkYTBiZjdiNGVmNDI0NDg4ZmEwZDkwZjMzNDAzZDIiLCJwIjoiaiJ9)
<br/>
-
<br/>
-
<br/>
[ATR-224]: https://attractorr.atlassian.net/browse/ATR-224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-224] feat: 마이페이지 API response 추가

---

src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java

feat: save 추가(Test용)

---

src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
src/main/java/run/attraction/api/v1/mypage/service/archive/newsletter/MypageNewsletterServiceImpl.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java

style: @Transactional 위치 수정

---

src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UserDetailDto.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java

style: 이름 통일 name=>nickname

---

src/main/java/run/attraction/api/v1/archive/AdminArticle.java
src/main/java/run/attraction/api/v1/archive/Article.java

<br/>
- [ATR-226](https://attractorr.atlassian.net/browse/ATR-226?atlOrigin=eyJpIjoiOGRkNTdkNGMxZGMxNDFjYWE3ZmQ0OGQ0YmIzMGQzMjkiLCJwIjoiaiJ9)
<br/>
- [[ATR-226] feat: Article/AdminArticle entity 수정](https://github.com/Atractorrr/Attraction-Server/commit/db7ebe8dcf8d2d2e04d6d470dc2fd44143d124fc) 
adminArticle
- length 100 -> 200
Article
- column 속성추가
- name = is_deleted, columnDefinition = "TINYINT(1) default 0"
<br/>
-
<br/>
[ATR-226]: https://attractorr.atlassian.net/browse/ATR-226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATR-226]: https://attractorr.atlassian.net/browse/ATR-226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-226] : Article/AdminArticle entity 수정

---

src/main/java/run/attraction/api/v1/archive/AdminArticle.java
src/main/java/run/attraction/api/v1/archive/Article.java

<br/>
- [ATR-226]
<br/>
- adminArticle
- length 100 -> 200 Article
- column 속성추가
- name = is_deleted, columnDefinition = "TINYINT(1) default 0"
<br/>
-
<br/>
[ATR-226]: https://attractorr.atlassian.net/browse/ATR-226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-226] feat: Article/AdminArticle entity 수정 (#90)

---

src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/introduction/UserSubscribedNewsletterCategory.java
src/main/java/run/attraction/api/v1/introduction/repository/UserSubscribedNewsletterCategoryRepository.java

<br/>
- [ATR-241](https://attractorr.atlassian.net/browse/ATR-241?atlOrigin=eyJpIjoiMDUwMDAyOGU3NGRmNDQ0ZWFhMGIzYmI3NmVkOGU4ZjEiLCJwIjoiaiJ9)
<br/>
- [[ATR-241] feat: 유저가 구독한 뉴스레터 카테고리 entity 구현](https://github.com/Atractorrr/Attraction-Server/pull/92/commits/407946eb10d567881e6c4ac66a1abc25dd74c712)
[407946e](https://github.com/Atractorrr/Attraction-Server/pull/92/commits/407946eb10d567881e6c4ac66a1abc25dd74c712)
- [[ATR-241] feat: UserSubscribedNewsletterCategoryRepository 추가](https://github.com/Atractorrr/Attraction-Server/pull/92/commits/ac8b2d3a35a7ea0215b0619c2ddf021e5cdcbcd4)
[ac8b2d3](https://github.com/Atractorrr/Attraction-Server/pull/92/commits/ac8b2d3a35a7ea0215b0619c2ddf021e5cdcbcd4)
- [[ATR-241] feat: 유저가 구독하는 뉴스레터 카테고리 저장 기능 …

[ATR - 241] feat: 유저가 구독한 뉴스레터 카테고리 저장

---

src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java

<br/>
- [ATR-243](https://attractorr.atlassian.net/browse/ATR-243?atlOrigin=eyJpIjoiZWFlYzJiNTY2ODU2NGIyYThmOTlhNGZlNjQ1ZGYyODEiLCJwIjoiaiJ9)
<br/>
- [[ATR-243] feat: 유저가 구독한 뉴스레터의 카테고리만 가져오기](https://github.com/Atractorrr/Attraction-Server/pull/94/commits/e3ad24a006e1f47d16481d190ae8462aafd743a4)
<br/>
-
<br/>
[ATR-243]: https://attractorr.atlassian.net/browse/ATR-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-243] feat: 유저가 구독한 뉴스레터의 카테고리만 가져오기

---

src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/resources/data.sql

<br/>
- [ATR-243](https://attractorr.atlassian.net/browse/ATR-243?atlOrigin=eyJpIjoiZWFlYzJiNTY2ODU2NGIyYThmOTlhNGZlNjQ1ZGYyODEiLCJwIjoiaiJ9)
<br/>
- [chore: 엔티티 변경으로 테스트 데이터 더미 일부 변경](https://github.com/Atractorrr/Attraction-Server/pull/95/commits/6c2141311f986a046c130e742359ff577a8a2e04)
[6c21413](https://github.com/Atractorrr/Attraction-Server/pull/95/commits/6c2141311f986a046c130e742359ff577a8a2e04)
- [[ATR-243] feat: 유저가 구독한 뉴스레터의 카테고리만 가져오기 (](https://github.com/Atractorrr/Attraction-Server/pull/95/commits/799eb51b97f4cdc155a1d19d75a56733e2748657)
<br/>
-
<br/>
[ATR-243]: https://attractorr.atlassian.net/browse/ATR-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATR-243]: https://attractorr.atlassian.net/browse/ATR-243?atlOrigin=eyJpI …

[ATR-243] feat: 유저가 구독한 뉴스레터의 카테고리만 가져오기 (#94)

---

src/main/java/run/attraction/api/v1/auth/controller/AuthController.java

style: 로그인 반환값 로그 작업

---

src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/introduction/exception/ErrorMessages.java

<br/>
-
<br/>
- [[ATR-246] feat: 단일의 유저 아티클 가져오는 기능 구현](https://github.com/Atractorrr/Attraction-Server/pull/99/commits/6f216b98b4e86ee1bdbb944c2f00b8f05178e1bc) 
[6f216b9](https://github.com/Atractorrr/Attraction-Server/pull/99/commits/6f216b98b4e86ee1bdbb944c2f00b8f05178e1bc)
유저가 아티클을 보러 바로 링크로 접근 했을 때 아티클 return
- [[ATR-246] feat: 에러메시지 추가](https://github.com/Atractorrr/Attraction-Server/pull/99/commits/9dd765e15996b04beefb7d52deaf719834080ed7) 
[9dd765e](https://github.com/Atractorrr/Attraction-Server/pull/99/commits/9dd765e15996b04beefb7d52deaf719834080ed7)
존재 하지 않는 아티클입니다
<br/>
-
<br/>
[ATR-246]: https://attractorr.atlassian.net/browse/ATR-246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATR-246]: …

[ATR-246] feat: 유저가 url로 바로 들어왔을 때 아티클 볼수있도록  API 기능 구현

---

src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/introduction/exception/ErrorMessages.java

<br/>
- [ATR-246](https://attractorr.atlassian.net/browse/ATR-246?atlOrigin=eyJpIjoiNDMzYjE2ZTRlM2MwNGY4ZGE3NTZlNTJlZWVjODYwMTIiLCJwIjoiaiJ9)
<br/>
- * [ATR-246] feat: 단일의 유저 아티클 가져오는 기능 구현
유저가 아티클을 보러 바로 링크로 접근 했을 때 아티클 return
- * [ATR-246] feat: 에러메시지 추가
존재 하지 않는 아티클입니다
<br/>
-
<br/>
[ATR-246]: https://attractorr.atlassian.net/browse/ATR-246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATR-246]: https://attractorr.atlassian.net/browse/ATR-246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATR-246]: https://attractorr.atlassian.net/browse/ATR-246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-246] feat: 유저가 url로 바로 들어왔을 때 아티클 볼수있도록  API 기능 구현 (#99)

---

src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
src/main/java/run/attraction/api/v1/auth/controller/AuthTestController.java

feat: 테스토용 UserDetail 삭제 API

---

src/main/java/run/attraction/api/v1/auth/controller/AuthTestController.java
src/main/java/run/attraction/api/v1/home/controller/HomeController.java

style: 테스트용 쿠키 확인 API

---

src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java
src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/UserArticleImg.java

style: 마이페이지 API 로그 테스트

---

src/main/java/run/attraction/api/v1/auth/token/repository/GoogleRefreshTokenRepository.java
src/main/java/run/attraction/api/v1/gmail/GmailClient.java

<br/>
- ATR-254
<br/>
- 라벨, 필터링시 이미 존재하는 값이 있으면 409 상태코드를 google에서 반환합니다.
- 따라서 이미 존재하는 라벨 혹은 필터가 존재하면 기존 라벨과 필터를 사용합니다.
<br/>
-
<br/>

[ATR-254] fix: 라벨, 필터 등록시 409 문제

---

src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
src/main/java/run/attraction/api/v1/archive/dto/request/UserArticlesRequest.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
src/main/resources/data.sql

<br/>
- [ATR-255](https://attractorr.atlassian.net/browse/ATR-255?atlOrigin=eyJpIjoiMmQ5YThlODg3NDY1NDdiMThhMWUxNjRlN2M0NDU1YWUiLCJwIjoiaiJ9)
<br/>
- [[ATR-255] feat: userEmail UserArticlesRequest dto에서 제거](https://github.com/Atractorrr/Attraction-Server/commit/134e5d1e484e10bc56ee31ebbb4c03e1592acef0)
- [[ATR-255] feat: 아티클 필터 로직 수정](https://github.com/Atractorrr/Attraction-Server/commit/2c0d03ffe8bc1ee53cca9bd8170bc023394044ef) 
- 전체적으로 readBox 의존성 최소화 -> leftjoin 사용
- predicate 시작점 변경 readBox -> article
- 카테고리 정상적으로 필터되도록 수정
- 읽은글 숨기기 필터 로직 수정
- readBox가 없어도 동작하도록 수정
- [[ATR-255] chore: 더미 데이터 수정](https://github.com/Atractorrr/Attraction-Server/commit/c8cdc5afee83a61f9552f03482660be3f5aa801e)
<br/>
-
<br/>
[ATR-255]: https://attractorr.atlassian.net/browse/ATR-255?atlOrigin=eyJpIjoiNWRk …

[ATR-255] feat: 아티클 필터 수정

---

src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
src/main/java/run/attraction/api/v1/archive/dto/request/UserArticlesRequest.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
src/main/resources/data.sql

<br/>
- [ATR-255](https://attractorr.atlassian.net/browse/ATR-255?atlOrigin=eyJpIjoiMmQ5YThlODg3NDY1NDdiMThhMWUxNjRlN2M0NDU1YWUiLCJwIjoiaiJ9)
<br/>
* [ATR-255] feat: userEmail UserArticlesRequest dto에서 제거
* [ATR-255] feat: 아티클 필터 로직 수정
- 전체적으로 readBox 의존성 최소화 -> leftjoin 사용
- predicate 시작점 변경 readBox -> article
- 카테고리 정상적으로 필터되도록 수정
- 읽은글 숨기기 필터 로직 수정
- readBox가 없어도 동작하도록 수정
* [ATR-255] chore: 더미 데이터 수정
<br/>
-
<br/>
[ATR-255]: https://attractorr.atlassian.net/browse/ATR-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATR-255]: https://attractorr.atlassian.net/browse/ATR-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATR-255]: https://attractorr.atlassian.net/browse/ATR-255?atlOrigin=eyJpIj …

[ATR-255] feat: 아티클 필터 수정 (#106)

---

src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
src/main/java/run/attraction/api/v1/user/repository/UserDetailRepository.java

<br/>
- [ATR-257](https://attractorr.atlassian.net/browse/ATR-257?atlOrigin=eyJpIjoiM2I5ZmRhMThlYjQ1NDcwYWI5OTMyZWE5ZWE0OGY4OWYiLCJwIjoiaiJ9)
<br/>
- 
<br/>
-
<br/>
[ATR-257]: https://attractorr.atlassian.net/browse/ATR-257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-257] feat: Transactional 동시성 문제 임시 해결 (DB Lock)

---

src/main/java/run/attraction/api/v1/home/service/dto/article/ArticleDetailDto.java

style : readingPercentage -> readPercentage

---

src/main/java/run/attraction/api/v1/archive/ReadBox.java
src/main/java/run/attraction/api/v1/archive/dto/ArticleDTO.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
src/main/java/run/attraction/api/v1/archive/repository/ReadBoxRepository.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java
src/main/resources/data.sql

<br/>
-
<br/>
- [style: readBox 변수명 변경 percentage-> readPercentage](https://github.com/Atractorrr/Attraction-Server/commit/0ce21527099e02d48674518fe03998d2cbbc9429)
<br/>
-
<br/>

style: readBox 변수명 변경 percentage-> readPercentage

---

src/main/java/run/attraction/api/v1/archive/ReadBox.java
src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
src/main/java/run/attraction/api/v1/archive/dto/ArticleDTO.java
src/main/java/run/attraction/api/v1/archive/dto/NewsletterDTO.java
src/main/java/run/attraction/api/v1/archive/repository/ReadBoxRepository.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java

<br/>
-
<br/>
- [style: 오타 수정 thumbnail -> thumbnailUrl](https://github.com/Atractorrr/Attraction-Server/commit/52de9433afc3fac9a7d31c5855e57cbcba711f7b)
- [fix: 삭제되었던 Query 다시 추가](https://github.com/Atractorrr/Attraction-Server/commit/89f96166a1905a2d2f31da3976f65ed9680a0d29) 
- findByUserEmailAndArticleId 메서드 쿼리 추가
- [style: 오타 수정 percentage -> readPercentage](https://github.com/Atractorrr/Attraction-Server/commit/9ca001d48dbe00a756d402e8452f633f052f4db1)
<br/>
-
<br/>

style: 오타 수정

---

src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
src/main/java/run/attraction/api/v1/auth/service/AuthService.java
src/main/java/run/attraction/api/v1/auth/service/helper/JoinHelper.java
src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
src/main/java/run/attraction/api/v1/user/UserDetail.java
src/main/java/run/attraction/api/v1/user/validator/exception/InvalidNicknameException.java
src/main/java/run/attraction/api/v1/user/validator/exception/InvalidNicknameExceptionHandler.java
src/main/java/run/attraction/api/v1/user/validator/nickname/EnglishValidator.java
src/main/java/run/attraction/api/v1/user/validator/nickname/KoreanValidator.java
src/main/java/run/attraction/api/v1/user/validator/nickname/NicknameValidator.java
src/main/java/run/attraction/api/v1/user/validator/nickname/NumberValidator.java
src/main/java/run/attraction/api/v1/user/validator/nickname/SpecialValidator.java
src/test/java/run/attraction/api/v1/user/validator/NicknameValidatorTest.java

<br/>
- [ATR-262](https://attractorr.atlassian.net/browse/ATR-262?atlOrigin=eyJpIjoiZWJjNjk3ODE3ZTg4NGY3MTk4YzYzMDNkOWUwZGRiODIiLCJwIjoiaiJ9)
<br/>
- SpecialValidator : 특수문자가 포함되어 있는지 검사
- EnglishValidator : 영어가 포함되어 있는지 검사, 포함되어 있다면 글자 길이 검사 (4이상 20이하)
- KoreanValidator : 한글만 있는지 검사, 한글만 있다면 글자 길이 검사 (2이상 20이하)
- NumberValidator : 숫자만 포함되어 있는지 검사
- InvalidNicknameException : NicknameValidator가 발생시킬 예외
- 에외가 발생하면 StatusCode 409 와 각 경우마다의 에러 메세지 전달
<br/>
-
<br/>
[ATR-262]: https://attractorr.atlassian.net/browse/ATR-262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-262] feat: nickname validator 생성 및 적용

---

src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
src/main/java/run/attraction/api/v1/auth/service/AuthService.java
src/main/java/run/attraction/api/v1/auth/service/helper/JoinHelper.java
src/main/java/run/attraction/api/v1/home/service/dto/article/ArticleDetailDto.java
src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
src/main/java/run/attraction/api/v1/user/UserDetail.java
src/main/java/run/attraction/api/v1/user/validator/exception/InvalidNicknameException.java
src/main/java/run/attraction/api/v1/user/validator/exception/InvalidNicknameExceptionHandler.java
src/main/java/run/attraction/api/v1/user/validator/nickname/EnglishValidator.java
src/main/java/run/attraction/api/v1/user/validator/nickname/KoreanValidator.java
src/main/java/run/attraction/api/v1/user/validator/nickname/NicknameValidator.java
src/main/java/run/attraction/api/v1/user/validator/nickname/NumberValidator.java
src/main/java/run/attraction/api/v1/user/validator/nickname/SpecialValidator.java
src/test/java/run/attraction/api/v1/user/validator/NicknameValidatorTest.java

<br/>
- [ATR-261](https://attractorr.atlassian.net/browse/ATR-261?atlOrigin=eyJpIjoiOTg5YjZlZTdiZGVjNDk0Y2IyZjRlZGVkNTFhMGZjZGMiLCJwIjoiaiJ9)
- [ATR-262](https://attractorr.atlassian.net/browse/ATR-262?atlOrigin=eyJpIjoiNjM3MjA2MDg1ZWM0NGFlNzk0ZjU1MTkyMDcyZjRmMGEiLCJwIjoiaiJ9)
<br/>
1. readingTime = 0 인 경우도 반영 
- readingTime : 해당 아티클을 읽는데 걸리는 시간
- 수정 전 : readingTime = 0 인 경우를 예외처리 했음
- 수정 후 : readingTime = 0 인 경우는 FE에서 1분미만 이라고 표시할 예정이기 때문에, 0인 경우를 예외처리하며 안됨.
- 변경 사항 : 음수인 경우에만 예외처리함.
2. nickname validator 생성 및 적용 
- SpecialValidator : 특수문자가 포함되어 있는지 검사
- EnglishValidator : 영어가 포함되어 있는지 검사, 포함되어 있다면 글자 길이 검사 (4이상 20이하)
- KoreanValidator : 한글만 있는지 검사, 한글만 있다면 글자 길이 검사 (2이상 20이하)
- NumberValidator : 숫자만 포함되어 있는지 검사
<br/>
-
<br/>
[ATR-261]: …

[ATR-211] feat: nickname Validator 적용 및 readingTime 관련 수정

---

.github/workflows/pull_request.yml

<br/>
- [ATR-275](https://attractorr.atlassian.net/browse/ATR-276?atlOrigin=eyJpIjoiZWU3ZmI0MDAxMjk3NDRlZjlmN2QxYTRjZjhjOTliM2UiLCJwIjoiaiJ9)
<br/>
- [dev 브랜치에 pull request 할때 빌드 및 테스트 진행](https://github.com/Atractorrr/Attraction-Server/commit/15e6d6d2ec1ab5a4d98067f369485618498ece9f)
<br/>
-
<br/>
[ATR-275]: https://attractorr.atlassian.net/browse/ATR-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-275] chore: dev 브랜치에 pull request 할때 빌드 및 테스트 진행

---

.github/workflows/deploy.yml

- github-token -> token
- log_url -> ref
<br/>
-
<br/>
-
<br/>
-
<br/>

chore: deploy.yml 잘못된 설정 수정

---

.github/workflows/deploy.yml

chore: deploy.yml 파일 수정

---

src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
src/main/java/run/attraction/api/v1/user/UserDetail.java

<br/>
- [ATR-274](https://attractorr.atlassian.net/browse/ATR-274?atlOrigin=eyJpIjoiYTdlNTlmMDkzMTM5NDM0MmI5Y2UyNDliZjdhOTc0OWQiLCJwIjoiaiJ9)
<br/>
- 중복 체크시 대소문자가 구분되지 않은 현상 발생
- MariaDB와 MySQL은 필드를 기본 VARCHAR로 생생하면 검색시 대소문자를 구분하지 않는다.
- 문자열 컬럼에서 대소문자를 구분하기 위해 binary 옵션 추가
<br/>
-
<br/>
[ATR-274]: https://attractorr.atlassian.net/browse/ATR-274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-274] feat: 닉네임 대소문자 구분 추가

---

src/main/java/run/attraction/api/v1/archive/AdminArticle.java
src/main/java/run/attraction/api/v1/archive/Article.java
src/main/java/run/attraction/api/v1/auth/token/GoogleRefreshToken.java
src/main/java/run/attraction/api/v1/introduction/Newsletter.java
src/main/java/run/attraction/api/v1/user/User.java

<br/>
- [ATR-277](https://attractorr.atlassian.net/browse/ATR-277?atlOrigin=eyJpIjoiNTMyYmY2MzkwZGI3NGUyNDk0NGY4MzI5NGU4NDg4ZDYiLCJwIjoiaiJ9)
<br/>
- mysql에서는 boolean 타입을 따로 제공하지 않아서 boolean을 내부적으로 tinyint로 인식
- 그런다고 tinyint로 boolean을 해버리면 다른 DB플랫폼에서 인식 불가 따라서 변경
-
[ATR-277]: https://attractorr.atlassian.net/browse/ATR-277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-277] feat: DB TINYINT타입을 BOOLEAN 타입으로 변경

---

build.gradle
src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
src/test/java/run/attraction/api/v1/introduction/CategoryTest.java
src/test/java/run/attraction/api/v1/mypage/service/archive/MypageArticleServiceTest.java
src/test/java/run/attraction/api/v1/mypage/service/archive/MypageNewsletterSerivceTest.java
src/test/java/run/attraction/api/v1/mypage/service/calendar/MypageCalendarServiceTest.java
src/test/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceTest.java
src/test/java/run/attraction/api/v1/repository/NewsletterRepositoryTest.java
src/test/java/run/attraction/api/v1/user/validator/NicknameValidatorTest.java
src/test/resources/data-h2.sql

<br/>
- [ATR-268]
<br/>
-
<br/>
-
<br/>
[ATR-268]: https://attractorr.atlassian.net/browse/ATR-268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-268] test: 마이페이지 테스트 코드 추가

---

src/main/java/run/attraction/api/v1/archive/AdminArticle.java
src/main/java/run/attraction/api/v1/archive/Article.java
src/main/java/run/attraction/api/v1/archive/dto/ArticleDTO.java
src/main/java/run/attraction/api/v1/auth/token/GoogleRefreshToken.java
src/main/java/run/attraction/api/v1/introduction/Newsletter.java
src/main/java/run/attraction/api/v1/user/User.java

<br/>
-
<br/>
- [feat: thumbnail/content url prefix 추가](https://github.com/Atractorrr/Attraction-Server/commit/5ed361fe22ed7546a93717a46400258e18b1dc3c)
<br/>
-
<br/>

feat: thumbnail/content url prefix 추가

---

src/main/java/run/attraction/api/v1/archive/dto/ArticleDTO.java
src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java

- thumbnail/ article url에 / 추가
<br/>
-
<br/>
- [fix: 오타 수정](https://github.com/Atractorrr/Attraction-Server/commit/7663a5a43785a862735e4663acb16a85297ea6ed) 
- thumbnail/ article url에 / 추가
<br/>
-
<br/>

fix: 오타 수정

---

.github/workflows/pull_request.yml
build.gradle
src/main/java/run/attraction/api/v1/introduction/UserSubscribedNewsletterCategory.java
src/test/java/run/attraction/api/v1/introduction/repository/NewsletterRepositoryTest.java

<br/>
- [ATR-267](https://attractorr.atlassian.net/browse/ATR-267?atlOrigin=eyJpIjoiMWI3MjQ2MDMwZDI3NDhiMzkxNWU1YThiYThiNGI3MjgiLCJwIjoiaiJ9)
<br/>
- [chore: 테스트를 위한 h2 패키지 추가](https://github.com/Atractorrr/Attraction-Server/commit/440e87aaaacc014a37b5eac4b6265b9058deab77)
- [test: NewsletterRepository 테스트 추가](https://github.com/Atractorrr/Attraction-Server/commit/2d181af3e39bde75c1973e10fb0598ff0872b92c)
-
<br/>
[ATR-267]: https://attractorr.atlassian.net/browse/ATR-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-267] test: NewsletterRepository 테스트 추가

---

src/test/java/run/attraction/api/v1/introduction/repository/UserSubscribedNewsletterCategoryRepositoryTest.java

<br/>
- [ATR-289](https://attractorr.atlassian.net/browse/ATR-289?atlOrigin=eyJpIjoiMWYzOWYyYThkZjFhNDU3ZWI3MGQ0N2FhYzgwYjAyM2UiLCJwIjoiaiJ9)
<br/>
- [test: UserSubscribedNewsletterCategoryRepository 테스트 추가](https://github.com/Atractorrr/Attraction-Server/commit/6a6ba7941592f6e59e32beed7c425719638f45d5)
<br/>
-
<br/>
[ATR-289]: https://attractorr.atlassian.net/browse/ATR-289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-289] test: UserSubscribedNewsletterCategoryRepository 테스트 추가

---

.github/workflows/pull_request.yml
build.gradle
src/main/java/run/attraction/api/v1/introduction/UserSubscribedNewsletterCategory.java
src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
src/main/java/run/attraction/api/v1/user/repository/UserDetailRepository.java
src/test/java/run/attraction/api/v1/introduction/repository/NewsletterRepositoryTest.java
src/test/java/run/attraction/api/v1/introduction/repository/UserSubscribedNewsletterCategoryRepositoryTest.java

feat: 동시성 테스트(DB Lock 해제)

---

src/main/java/run/attraction/api/v1/archive/repository/ReadBoxRepository.java
src/main/java/run/attraction/api/v1/rank/ExtensiveRank.java
src/main/java/run/attraction/api/v1/rank/controller/RankController.java
src/main/java/run/attraction/api/v1/rank/repository/ExtensiveRankRepository.java
src/main/java/run/attraction/api/v1/rank/service/RankCalculator.java
src/main/java/run/attraction/api/v1/rank/service/RankService.java
src/main/java/run/attraction/api/v1/rank/service/dto/ExtensiveRankResponseDto.java
src/main/java/run/attraction/api/v1/rank/service/dto/RankDetailDto.java
src/main/java/run/attraction/api/v1/user/repository/UserRepository.java

<br/>
- [ATR-284](https://attractorr.atlassian.net/browse/ATR-284?atlOrigin=eyJpIjoiYTQ0N2MxMzFhMzUxNGNjZDgyYmEwMzExOWNmYTQzZjIiLCJwIjoiaiJ9)
<br/>
- 다독 랭킹 : 가장 많이 읽은 유저 Top 10
- 랭크 매달 초기화되며, 매일 랭킹이 갱신됨
- 조회한 날짜의 하루 전까지의 데이터로 랭크 계산
<br/>
-
<br/>
[ATR-284]: https://attractorr.atlassian.net/browse/ATR-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-284] feat: 다독 랭킹 시스템 구현

---

src/main/java/run/attraction/api/v1/archive/repository/ReadBoxRepository.java
src/main/java/run/attraction/api/v1/rank/ExtensiveRank.java
src/main/java/run/attraction/api/v1/rank/controller/RankController.java
src/main/java/run/attraction/api/v1/rank/repository/ExtensiveRankRepository.java
src/main/java/run/attraction/api/v1/rank/service/RankCalculator.java
src/main/java/run/attraction/api/v1/rank/service/RankService.java
src/main/java/run/attraction/api/v1/rank/service/dto/ExtensiveRankResponseDto.java
src/main/java/run/attraction/api/v1/rank/service/dto/RankDetailDto.java
src/main/java/run/attraction/api/v1/user/repository/UserRepository.java

<br/>
- [ATR-283](https://attractorr.atlassian.net/browse/ATR-283?atlOrigin=eyJpIjoiYzA0YmI2Y2U1NjlmNGVkODk2MDQyZDQzNmQ5NzU1YTMiLCJwIjoiaiJ9)
<br/>
- 다독 랭크 시스템 구현
<br/>
-
<br/>
[ATR-283]: https://attractorr.atlassian.net/browse/ATR-283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-283] feat: 랭킹 시스템 구현 (다독 랭크)

---

src/main/java/run/attraction/api/v1/statistics/AgeGroupStatistics.java
src/main/java/run/attraction/api/v1/statistics/controller/StatisticsController.java
src/main/java/run/attraction/api/v1/statistics/repository/AgeGroupStatisticsRepository.java
src/main/java/run/attraction/api/v1/statistics/repository/NewsletterEventRepository.java
src/main/java/run/attraction/api/v1/statistics/service/StatisticsService.java
src/main/java/run/attraction/api/v1/statistics/service/ageGroup/AgeGroupStatisticsCalculator.java

<br/>
- [ATR-299](https://attractorr.atlassian.net/browse/ATR-299?atlOrigin=eyJpIjoiZDc1ODlmNDJmMWQ0NDg3NzlmMzZjMjNhOTNjNDg3MTYiLCJwIjoiaiJ9)
<br/>
- `AgeGroupStatistics`
- NewsletterEvent에서 조회한 "연령별 인기 있는 뉴스레터"를 저장하는 테이블
- createdAt으로 생성날짜 구분
- `AgeGroupStatisticsCalculator`
- NewsletterEventRepository의 데이터로 조회
- 연령별 가장 인기 있는 뉴스레터를 하나씩 계산
<br/>
-
<br/>
[ATR-299]: https://attractorr.atlassian.net/browse/ATR-299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-299] feat: 연령별 통계 시스템 구현

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
src/main/java/run/attraction/api/v1/bookmark/Bookmark.java
src/main/java/run/attraction/api/v1/bookmark/controller/BookmarkController.java
src/main/java/run/attraction/api/v1/bookmark/dto/BookmarkArticleRequest.java
src/main/java/run/attraction/api/v1/bookmark/exception/BookmarkExceptionHandler.java
src/main/java/run/attraction/api/v1/bookmark/repository/BookmarkRepository.java
src/main/java/run/attraction/api/v1/bookmark/service/BookmarkService.java
src/main/java/run/attraction/api/v1/introduction/exception/ErrorMessages.java
src/test/java/run/attraction/api/v1/bookmark/repository/BookmarkRepositoryTest.java
src/test/java/run/attraction/api/v1/bookmark/service/BookmarkServiceTest.java
src/test/resources/sql/bookmark/bookmark-service-test-data.sql

<br/>
- [ATR-313](https://attractorr.atlassian.net/browse/ATR-313?atlOrigin=eyJpIjoiYWYxYmFlMDA3ZGM2NDJjMWFiOWQzNjRkNTA1ZGU4YTUiLCJwIjoiaiJ9)
<br/>
- 기능 구현
- 북마크 추가
- 북마크 삭제
- 북마크 여부 확인
- 북마크한 아티클 가져오기
- 예외 처리
- 테스트 코드
<br/>
-
<br/>
[ATR-313]: https://attractorr.atlassian.net/browse/ATR-313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-313] feat: bookmark API 추가

---

src/main/java/run/attraction/api/v1/rank/ConsistencyRank.java
src/main/java/run/attraction/api/v1/rank/ExtensiveRank.java
src/main/java/run/attraction/api/v1/rank/Rank.java
src/main/java/run/attraction/api/v1/rank/ReadBoxEvent.java
src/main/java/run/attraction/api/v1/rank/controller/RankController.java
src/main/java/run/attraction/api/v1/rank/repository/ConsistencyRankRepository.java
src/main/java/run/attraction/api/v1/rank/repository/ReadBoxEventRepository.java
src/main/java/run/attraction/api/v1/rank/service/RankService.java
src/main/java/run/attraction/api/v1/rank/service/calculator/ConsistencyRankCalculator.java
src/main/java/run/attraction/api/v1/rank/service/calculator/ExtensiveRankCalculator.java
src/main/java/run/attraction/api/v1/rank/service/dto/RankResponseDto.java

<br/>
- [ATR-295](https://attractorr.atlassian.net/browse/ATR-295?atlOrigin=eyJpIjoiYWJjODRlZjBhMzgzNDQ1MzgxNGRhZjg1Nzk4YjY5MmIiLCJwIjoiaiJ9)
<br/>
- `ReadBoxEvent`
- 사용자가 "몇일 연속으로 아티클을 읽었는지"에 대한 데이터 가지고 있다.
- 매월 초기화
- `ConsistencyRank`
- 꾸준함 랭크 정보 가지고 있다.
- createdAt으로 랭크 정보를 구분 
- `ConsistencyRankCalculator`
- ConsistencyRankRepository에 정보가 없을시 계산
- consistency_rank_readbox_event에서 데이터를 읽어 Top 10 계산
<br/>
-
<br/>
[ATR-295]: https://attractorr.atlassian.net/browse/ATR-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-295] feat: 꾸준함(스프린트) 랭킹시스템 구현

---

src/main/java/run/attraction/api/v1/archive/repository/ReadBoxRepository.java

<br/>
- [ATR-284](https://attractorr.atlassian.net/browse/ATR-284?atlOrigin=eyJpIjoiN2U4ODFhMGNjZGMxNDM4YmE2NTQ5ZDFhOGRjNjQxZjkiLCJwIjoiaiJ9)
<br/>
- ReadBoxRepository에서 상위 10개만 추출하도록 수정
<br/>
-
<br/>
[ATR-284]: https://attractorr.atlassian.net/browse/ATR-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-284] feat: 다독 랭킹 시스템 수정

---

src/main/java/run/attraction/api/v1/archive/repository/ReadBoxRepository.java
src/main/java/run/attraction/api/v1/rank/ConsistencyRank.java
src/main/java/run/attraction/api/v1/rank/Rank.java
src/main/java/run/attraction/api/v1/rank/ReadBoxEvent.java
src/main/java/run/attraction/api/v1/rank/controller/RankController.java
src/main/java/run/attraction/api/v1/rank/repository/ConsistencyRankRepository.java
src/main/java/run/attraction/api/v1/rank/repository/ReadBoxEventRepository.java
src/main/java/run/attraction/api/v1/rank/service/RankService.java
src/main/java/run/attraction/api/v1/rank/service/calculator/ConsistencyRankCalculator.java
src/main/java/run/attraction/api/v1/rank/service/calculator/ExtensiveRankCalculator.java
src/main/java/run/attraction/api/v1/rank/service/dto/RankResponseDto.java

<br/>
- [ATR-295](https://attractorr.atlassian.net/browse/ATR-295?atlOrigin=eyJpIjoiMzg0MjMzMGFiZDZhNGU5NGFmNzU1NjI0Y2JkZTkwNDkiLCJwIjoiaiJ9)
<br/>
- 꾸준함(스프린트) 랭킹시스템 구현
<br/>
-
<br/>
[ATR-295]: https://attractorr.atlassian.net/browse/ATR-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-283] feat: 꾸준함(스프린트) 랭킹시스템 구현

---

src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UserDetailDto.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
src/main/resources/data.sql
src/test/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceTest.java

<br/>
- [ATR-343](https://attractorr.atlassian.net/browse/ATR-343?atlOrigin=eyJpIjoiYjJmNTExNDU1NGY3NGI4MmJhNDhjMmJhYmI4NWNlYzAiLCJwIjoiaiJ9)
<br/>
- 개인설정 변경으로 인한 api 수정
- 반환 데이터 추가
- userExpirationDate : 유저 계정 만료일(날짜 형식)
- agreeAt : 약관 동의한 날
<br/>
-
<br/>
[ATR-343]: https://attractorr.atlassian.net/browse/ATR-343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-343] feat: 사용자 정보 반환 api 수정

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/home/controller/HomeController.java
src/main/java/run/attraction/api/v1/home/service/HomeService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterService.java
src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterServiceImpl.java
src/main/java/run/attraction/api/v1/introduction/repository/NewsletterRepository.java

<br/>
- [ATR-328](https://attractorr.atlassian.net/browse/ATR-328?atlOrigin=eyJpIjoiOWNmN2IwYjZiMzBhNDBkNjhmNWI3YTNmMDA2MTIwYmMiLCJwIjoiaiJ9)
<br/>
- `아티클 통합 검색`
- 요청받은 텍스트(search)를 기준으로 아티클 검색
- 최신순으로 정렬 (receivedAt DESC )
- `뉴스레터 통합 검색`
- 요청받은 텍스트(search)를 기준으로 뉴스레터 이름 검색
<br/>
-
<br/>
[ATR-328]: https://attractorr.atlassian.net/browse/ATR-328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-328] feat: 메인페이지 통합 검색 시스템 구현

---

src/main/java/run/attraction/api/v1/introduction/controller/IntroductionController.java
src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java

<br/>
- [ATR-319](https://attractorr.atlassian.net/browse/ATR-319?atlOrigin=eyJpIjoiOGFjYjBhMzc4ZjQ5NGRiMWE5YTNiZGEwYmFkMzlmYmIiLCJwIjoiaiJ9)
<br/>
- 지난 아티클 상세조회 API 추가
- 
<br/>
-
<br/>
[ATR-319]: https://attractorr.atlassian.net/browse/ATR-319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-319] feat: 지난 아티클 상세 조회 API 구현

---

src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/introduction/exception/ErrorMessages.java

이미 구독한 뉴스레터를 구독할 시 예외처리
<br/>
- [ATR-371](https://attractorr.atlassian.net/browse/ATR-371?atlOrigin=eyJpIjoiMDdlMzNkOWU2OGQxNDVjZmFkODU5M2I1OWNhYmFiMDgiLCJwIjoiaiJ9)
<br/>
- 이미 구독한 뉴스레터를 구독할 시 예외처리
<br/>
-
<br/>
[ATR-371]: https://attractorr.atlassian.net/browse/ATR-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-371] feat: 구독리스트에 뉴스레터 중복 추가 제한

---

src/main/java/run/attraction/api/v1/introduction/exception/GlobalExceptionHandler.java
src/test/java/run/attraction/api/v1/globalException/GlobalExceptionHandlerTest.java
src/test/java/run/attraction/api/v1/globalException/TestController.java

<br/>
- [ATR-373](https://attractorr.atlassian.net/browse/ATR-373?atlOrigin=eyJpIjoiYmNiNmY3MzdlM2RjNGFjZmIxODFhNGUyM2Y2ZTA5ZDMiLCJwIjoiaiJ9)
<br/>
- 추가된 예외처리
- IllegalArgumentException
- MethodArgumentNotValidException
- HttpRequestMethodNotSupportedException
- ConstrainViolationException
- 에러 관련 정보 추가
- timestamp
- status
- error
- 테스트 코드
<br/>
-
<br/>
[ATR-373]: https://attractorr.atlassian.net/browse/ATR-373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-373] feat: 글로벌 예외 처리 개선

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/home/controller/HomeController.java
src/main/java/run/attraction/api/v1/home/service/HomeService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java

<br/>
- [ATR-394](https://attractorr.atlassian.net/browse/ATR-394?atlOrigin=eyJpIjoiMDA3OTI1MjljYmE5NDI3M2I3N2QxYTFjMmEyYTUwY2EiLCJwIjoiaiJ9)
<br/>
- 추가사항으로 아티클 content summary 추가 전달
<br/>
-
<br/>
[ATR-394]: https://attractorr.atlassian.net/browse/ATR-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-394] feat: 아티클 검색 DTO 수정

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/home/controller/HomeController.java
src/main/java/run/attraction/api/v1/home/service/HomeService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java

<br/>
- [ATR-394](https://attractorr.atlassian.net/browse/ATR-394?atlOrigin=eyJpIjoiMDA3OTI1MjljYmE5NDI3M2I3N2QxYTFjMmEyYTUwY2EiLCJwIjoiaiJ9)
<br/>
- 추가사항으로 아티클 content summary 추가 전달
<br/>
-
<br/>
[ATR-394]: https://attractorr.atlassian.net/browse/ATR-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-394] feat: 아티클 검색 DTO 수정 

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/home/controller/HomeController.java
src/main/java/run/attraction/api/v1/home/service/HomeService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
src/main/java/run/attraction/api/v1/home/service/dto/search/ArticleSearchDto.java
src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java

<br/>
- [ATR-394](https://attractorr.atlassian.net/browse/ATR-394?atlOrigin=eyJpIjoiMDA3OTI1MjljYmE5NDI3M2I3N2QxYTFjMmEyYTUwY2EiLCJwIjoiaiJ9)
<br/>
- ArticleSearchDto 생성
- s3 base url 추가
<br/>
-
<br/>
[ATR-394]: https://attractorr.atlassian.net/browse/ATR-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-394] feat: 아티클 검색 DTO 추가 수정

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/home/controller/HomeController.java
src/main/java/run/attraction/api/v1/home/service/HomeService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
src/main/java/run/attraction/api/v1/home/service/dto/search/ArticleSearchDto.java
src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java

<br/>
- [ATR-394](https://attractorr.atlassian.net/browse/ATR-394?atlOrigin=eyJpIjoiMDA3OTI1MjljYmE5NDI3M2I3N2QxYTFjMmEyYTUwY2EiLCJwIjoiaiJ9)
<br/>
- ArticleSearchDto 생성
- s3 base url 추가
<br/>
-
<br/>
[ATR-394]: https://attractorr.atlassian.net/browse/ATR-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-394] feat: 아티클 검색 DTO 추가 수정 

---

.gitignore
build.gradle
src/main/java/run/attraction/api/v1/auth/controller/FaviconController.java
src/main/java/run/attraction/api/v1/auth/filter/HttpLogMessage.java
src/main/java/run/attraction/api/v1/auth/filter/RequestLogFilter.java
src/main/resources/log4j2.xml

<br/>
- ATR-403
<br/>
- log4j2를 통해서 log를 파일로 관리하며 MDC를 통해서 사용자의 스레드 별로 로그를 분리합니다. (멀티 스레드에도 분리)
- 서블릿 필터를 통해서 request 시작과 끝에서 사용자 로그를 기록합니다.
<br/>
-
<br/>

[ATR-401] feat: monitoring system

---

.github/workflows/deploy.yml

<br/>
- [ATR-413](https://attractorr.atlassian.net/browse/ATR-413?atlOrigin=eyJpIjoiOGQ3YTE4NGIyYjEwNDE2Njg2NzM5MzVmMTM5NDNmNzUiLCJwIjoiaiJ9)
<br/>
- 로그를 docker volume을 통해 aws 디렉과 마운트
<br/>
-
<br/>
[ATR-413]: https://attractorr.atlassian.net/browse/ATR-413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-413] chore: github action 도커 볼륨을 aws 디렉토리와 마운트

---

.github/workflows/deploy.yml

<br/>
- #172  
<br/>
-
<br/>
-
<br/>

[ATR-413] chore: github action 도커 볼륨을 aws 디렉토리와 마운트 (#172)

---

src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/rank/service/calculator/ConsistencyRankCalculator.java
src/main/java/run/attraction/api/v1/statistics/controller/StatisticsController.java
src/main/java/run/attraction/api/v1/statistics/service/StatisticsService.java

<br/>
- [ATR-415](https://attractorr.atlassian.net/browse/ATR-415?atlOrigin=eyJpIjoiNWNiMDAxYTczZDdmNGMyNjk2ZTBjYWRhNWY0N2FlMmIiLCJwIjoiaiJ9)
<br/>
- ReadBox=100 인 경우 ReadBoxEvent 저장
- 유저의 꾸준함을 측정한 테이블로, modifiedAt를 보고 consistencyValue 갱신
<br/>
-
<br/>
[ATR-415]: https://attractorr.atlassian.net/browse/ATR-415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-415] feat: ReadBoxEvent 저장 로직 추가

---

.github/workflows/deploy.yml

<br/>
-
<br/>
- github action에 filebeat 도커 추가
<br/>
-
<br/>

chore: github action에 filebeat 도커 추가

---

.github/workflows/deploy.yml

<br/>
-
<br/>
- [chore: github action filebeat 도커 실행 순서 변경](https://github.com/Atractorrr/Attraction-Server/commit/427e7bef2ac3d27647d8c5690499cfbbcdd04959)
- [fix: filebeat 설정 상대경로를 절대경로로 변경](https://github.com/Atractorrr/Attraction-Server/commit/14abb2343c61071f871cee1baa7a4ab722366173)
<br/>
-
<br/>

fix: filebeat docker 설정 변경

---

.github/workflows/deploy.yml

<br/>
-
<br/>
- [fix: filebeat 도커 컨테이너 종료후 재실행하도록 변경](https://github.com/Atractorrr/Attraction-Server/commit/1b25833525777effd998a9a12683a9644c063a39)
<br/>
-
<br/>

fix: filebeat 도커 컨테이너 종료후 재실행하도록 변경

---

.github/workflows/deploy.yml

filebeat에 루트 권한 부여
<br/>
-
<br/>
- [chore: github action deploy 파일 수정](https://github.com/Atractorrr/Attraction-Server/commit/d1dd748b6b590311fcc7bb3ce1b46449cb09aa68) 
filebeat에 루트 권한 부여
<br/>
-
<br/>

chore: github action deploy 파일 수정

---

.github/workflows/deploy.yml

<br/>
-
<br/>
- [chore: filebeat docker 명령어 수정](https://github.com/Atractorrr/Attraction-Server/commit/6cc7c3d86108e9f0e456dc581906d41bf7442fcb)
<br/>
-
<br/>

chore: filebeat docker 명령어 수정

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/resources/data.sql
src/test/java/run/attraction/api/v1/bookmark/service/BookmarkServiceTest.java

<br/>
- [ATR-418](https://attractorr.atlassian.net/browse/ATR-418?atlOrigin=eyJpIjoiNjZmZDNlMjBhMzhkNDJlNmI1YTJjZTkyMmViYTYyMTgiLCJwIjoiaiJ9)
<br/>
-  [feat: findArticlesByUserId 메서드 수정](https://github.com/Atractorrr/Attraction-Server/commit/d11b5a832397c1f6610c2e568c20ed0757cc19bf)
<br/>
-
<br/>
[ATR-418]: https://attractorr.atlassian.net/browse/ATR-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-418] feat: findArticlesByUserId 메서드 수정

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleService.java
src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java
src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/RecentArticleNewsletterDto.java
src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/RecentArticlesDto.java
src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/RecentArticlesResponseDto.java
src/main/resources/data.sql

[[ATR-447] feat: 마이페이지 최근 읽은 아티클 로직 수정](https://github.com/Atractorrr/Attraction-Server/commit/197970ea64f7f23f676033088084c816f24af754)
[ATR-447]: https://attractorr.atlassian.net/browse/ATR-447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-447] feat: 마이페이지 최근 읽은 아티클 로직 수정 

---

src/main/java/run/attraction/api/v1/auth/service/helper/LoginHelper.java
src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserService.java
src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
src/main/java/run/attraction/api/v1/user/User.java

<br/>
-[ATR-448](https://attractorr.atlassian.net/browse/ATR-448?atlOrigin=eyJpIjoiMWYwNjQwMGZkYWNjNDA4M2FiYTI1MWZiYzE3ODk0MzEiLCJwIjoiaiJ9)
<br/>
- User : isDeleted가 true로 변환
- UserDetail : 삭제
<br/>
-
<br/>
[ATR-448]: https://attractorr.atlassian.net/browse/ATR-448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-448] feat: 회원 탈퇴 로직 추가

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
src/main/java/run/attraction/api/v1/home/controller/HomeController.java
src/main/java/run/attraction/api/v1/home/service/HomeService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticleNewsletterDto.java
src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticlesDto.java
src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticlesResponseDto.java

<br/>
- [ATR-449](https://attractorr.atlassian.net/jira/software/projects/ATR/boards/1?selectedIssue=ATR-449)
<br/>
- AdminArticle과 Article의 병합으로 기존에 메인페이지에서 보여주던  최근 받은 아티클 로직을 수정
- 더 이상 article id가 모든 사람을 기준으로 할 때 유니크 하지 않기 때문에 구독하고 있는 뉴스레터 먼저 확인해서 최종적으로 최근 받은 아티클을 가져오도록 변경
<br/>
-
<br/>
[ATR-449]: https://attractorr.atlassian.net/browse/ATR-449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-449] feat: 최근 받은 아티클 로직 수정 - 메인페이지

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
src/main/java/run/attraction/api/v1/home/controller/HomeController.java
src/main/java/run/attraction/api/v1/home/service/HomeService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticleNewsletterDto.java
src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticlesDto.java
src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticlesResponseDto.java

https://github.com/Atractorrr/Attraction-Server/pull/193

[ATR-449] feat: 최근 받은 아티클 로직 수정 (#193)

---

src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticleNewsletterDto.java
src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticlesDto.java
src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/RecentArticleNewsletterDto.java
src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/RecentArticlesDto.java

<br/>
-
<br/>
- newsletterThumbnailUrl에서 prefix 제거
- prefix :  Thumbnails -> thumbnail    변경
<br/>
-
<br/>

style: newsletterThumbnailUrl에서 prefix 제거

---

src/main/java/run/attraction/api/v1/archive/dto/ArticleDTO.java
src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java

<br/>
- [ATR-460](https://attractorr.atlassian.net/browse/ATR-460?atlOrigin=eyJpIjoiOGFiNGJkZDFkNTQxNDdiMzg4NTIyOWFjZTg3ZWNmN2MiLCJwIjoiaiJ9)
<br/>
- [article과 previousArticle에서 s3 prefix 제거](https://github.com/Atractorrr/Attraction-Server/commit/ad354b06cf2e71c517e503fe775c8c10c4704abe)
- 프론트에서 해당 prefix 관리
<br/>
<br/>
[ATR-460]: https://attractorr.atlassian.net/browse/ATR-460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-460] feat: article과 previousArticle에서 s3 prefix 제거

---

src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
src/main/java/run/attraction/api/v1/auth/session/SessionService.java
src/main/java/run/attraction/api/v1/auth/session/dto/UserDetailBySession.java
src/main/java/run/attraction/api/v1/auth/session/exception/SessionIdNotFoundException.java
src/main/java/run/attraction/api/v1/auth/session/exception/SessionIdNotFoundExceptionHandler.java
src/main/java/run/attraction/api/v1/exception/ErrorCode.java
src/main/java/run/attraction/api/v1/user/Interest.java
src/main/java/run/attraction/api/v1/user/repository/UserRepository.java

<br/>
- [ATR-461](https://attractorr.atlassian.net/browse/ATR-461?atlOrigin=eyJpIjoiYzcwMDViZjRmZTA5NGIxMmJlZWE0MTEyNDkxNTZmYmQiLCJwIjoiaiJ9)
- [ATR-458](https://attractorr.atlassian.net/browse/ATR-458?atlOrigin=eyJpIjoiZjNiZmYzN2U5NjhlNGIwZDhiNjY2YjE4M2VjZmJiMTYiLCJwIjoiaiJ9)
<br/>
- '건강/의학' 제거
- '경제' 추가
- 세션 Id로 유저 정보 조회 기능 추가
<br/>
-
<br/>
[ATR-461]: https://attractorr.atlassian.net/browse/ATR-461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATR-458]: https://attractorr.atlassian.net/browse/ATR-458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-271] feat: 유저 관심사 수정 및 세션 ID 유저 정보 조회 API 구현

---

src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
src/main/java/run/attraction/api/v1/auth/session/SessionService.java
src/main/java/run/attraction/api/v1/auth/session/dto/UserDetailBySession.java
src/main/java/run/attraction/api/v1/auth/session/exception/SessionIdNotFoundException.java
src/main/java/run/attraction/api/v1/auth/session/exception/SessionIdNotFoundExceptionHandler.java
src/main/java/run/attraction/api/v1/exception/ErrorCode.java
src/main/java/run/attraction/api/v1/user/Interest.java
src/main/java/run/attraction/api/v1/user/repository/UserRepository.java

<br/>
- [ATR-461](https://attractorr.atlassian.net/browse/ATR-461?atlOrigin=eyJpIjoiYzcwMDViZjRmZTA5NGIxMmJlZWE0MTEyNDkxNTZmYmQiLCJwIjoiaiJ9)
- [ATR-458](https://attractorr.atlassian.net/browse/ATR-458?atlOrigin=eyJpIjoiZjNiZmYzN2U5NjhlNGIwZDhiNjY2YjE4M2VjZmJiMTYiLCJwIjoiaiJ9)
<br/>
- '건강/의학' 제거
- '경제' 추가
- 세션 Id로 유저 정보 조회 기능 추가
<br/>
-
<br/>
[ATR-461]: https://attractorr.atlassian.net/browse/ATR-461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATR-458]: https://attractorr.atlassian.net/browse/ATR-458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: 유저 관심사 수정 및 세션 ID 유저 정보 조회 API 구현

---

src/main/java/run/attraction/api/v1/auth/filter/RequestLogFilter.java

<br/>
- ATR-475
<br/>
- prometheus uri 하드 코딩 제거
<br/>
-
<br/>

[ATR-475] refactor: prometheus uri 하드 코딩 제거

---

src/main/java/run/attraction/api/v1/auth/filter/RequestLogFilter.java

<br/>
- ATR-475
<br/>
- prometheus uri 하드 코딩 제거
<br/>
-
<br/>

[ATR-475] refactor: prometheus uri 하드 코딩 제거 (#203)

---

src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java

<br/>
- [ATR-448](https://attractorr.atlassian.net/browse/ATR-448?atlOrigin=eyJpIjoiMDlmNjQ3NTgxZWJhNDdmMmIzMWFjNWEyYzI4YzQzMWMiLCJwIjoiaiJ9)
<br/>
- 세션 제거 로직 추가
<br/>
-
<br/>
[ATR-448]: https://attractorr.atlassian.net/browse/ATR-448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-448] feat: 탈퇴 api 수정

---

src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java

<br/>
- [ATR-448](https://attractorr.atlassian.net/browse/ATR-448?atlOrigin=eyJpIjoiMDlmNjQ3NTgxZWJhNDdmMmIzMWFjNWEyYzI4YzQzMWMiLCJwIjoiaiJ9)
<br/>
- 세션 제거 로직 추가
<br/>
-
<br/>
[ATR-448]: https://attractorr.atlassian.net/browse/ATR-448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-448] feat: 탈퇴 api 수정 (#205)

---

src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/monitoring/MicrometerConfig.java
src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
src/main/java/run/attraction/api/v1/rank/controller/RankController.java
src/main/java/run/attraction/api/v1/rank/service/RankService.java

<br/>
- ATR-479
<br/>
- 중요한 메서드 모니터링
<br/>
-
<br/>

[ATR-479] feat: method monitoring

---

src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/monitoring/MicrometerConfig.java
src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
src/main/java/run/attraction/api/v1/rank/controller/RankController.java
src/main/java/run/attraction/api/v1/rank/service/RankService.java

<br/>
- ATR-479
<br/>
- 중요한 메서드 모니터링
<br/>
-
<br/>

[ATR-479] feat: method monitoring (#207)

---

src/main/java/run/attraction/api/v1/introduction/controller/SubscriptionController.java
src/main/java/run/attraction/api/v1/introduction/repository/SubscribeRepository.java
src/main/java/run/attraction/api/v1/introduction/service/SubscriptionService.java

<br/>
- [ATR-485](https://attractorr.atlassian.net/browse/ATR-485?atlOrigin=eyJpIjoiNTBiOWY1MmZjODc4NDc1NzlmOTU4NzRiNDllYzUzN2YiLCJwIjoiaiJ9)
<br/>
- 유저가 특정 뉴스레터를 구독했는지 확인해주는 메서드 추가
<br/>
-
<br/>
[ATR-485]: https://attractorr.atlassian.net/browse/ATR-485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-485] feat: 해당 뉴스레터 구독 여부 확인 메서드 추가

---

.github/workflows/deploy.yml

[chore: 슬랙 알림 추가](https://github.com/Atractorrr/Attraction-Server/commit/cab254ea315d8e550a2778208685f4499c57e827)

chore: 슬랙 알림 추가

---

src/main/java/run/attraction/api/v1/auth/config/SecurityConfig.java

<br/>
-
<br/>
- chore: SecurityConfig monitoring url 적용
<br/>
-
<br/>

chore: SecurityConfig monitoring url 적용

---

src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
src/main/java/run/attraction/api/v1/introduction/utils/SubscriptionUtil.java

[[ATR-502] fix: 아티클 보관함 및 최근 받은 아티클 에러 수정 ](https://github.com/Atractorrr/Attraction-Server/commit/573de63afffde505dacb79d138ee0091fb76f5b0)
[ATR-502]: https://attractorr.atlassian.net/browse/ATR-502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-502] fix: 아티클 보관함 및 최근 받은 아티클 에러 수정 (#222)

---

src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/introduction/controller/SubscriptionController.java
src/main/java/run/attraction/api/v1/introduction/service/SubscriptionService.java

<br/>
- [ATR-503](https://attractorr.atlassian.net/browse/ATR-503?atlOrigin=eyJpIjoiOWU4YTU0ZmNlZGUzNDE4YzgzNWU2N2MwNDg3NWMzYjMiLCJwIjoiaiJ9)
<br/>
- 뉴스레터를 구독하는 api archive -> subscription으로 파일이동
- 이름 변경 addNewsletter -> subscribeNewsletter
- 기존 하나의 메서드가 3가지일 수행 -> 3개의 메서드가 각 한 가지일 수행
<br/>
-
<br/>
[ATR-503]: https://attractorr.atlassian.net/browse/ATR-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-503] refactor: 뉴스레터 구독 api 리팩터링

---

src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/introduction/controller/SubscriptionController.java
src/main/java/run/attraction/api/v1/introduction/service/SubscriptionService.java

[[ATR-503] refactor: 뉴스레터 구독 api 리팩터링 ](https://github.com/Atractorrr/Attraction-Server/commit/72b101d827b2fa5196897cb2fc199232a0b6b864)
[ATR-503]: https://attractorr.atlassian.net/browse/ATR-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-503] refactor: 뉴스레터 구독 api 리팩터링 (#224)

---

.github/workflows/deploy.yml

<br/>
-
<br/>
- git 배포 일시적 비활성화
<br/>
-
<br/>

chore: github action git 배포 일시적 비활성화

---

.github/workflows/deploy.yml

[chore: github action git 배포 일시적 비활성화 ](https://github.com/Atractorrr/Attraction-Server/commit/a34346a81f8167a180a3144640dbf3d595462daa)

chore: github action git 배포 일시적 비활성화 (#226)

---

src/main/java/run/attraction/api/v1/introduction/service/SubscriptionService.java

<br/>
- [ATR-503](https://attractorr.atlassian.net/browse/ATR-503?atlOrigin=eyJpIjoiOGQ3YTliZWE4NzM5NDYwNWI2MzYxOTE2ODlmOTQ1N2MiLCJwIjoiaiJ9)
<br/>
- 뉴스레터가 자동구독이 가능할 때만 카프카 메시지 전송
<br/>
-
<br/>
[ATR-503]: https://attractorr.atlassian.net/browse/ATR-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-503] feat: 자동 구독이 가능할 때만 카프카메시지 전송해서 동작하도록 수정

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/home/service/dto/search/ArticleSearchDto.java

- contentUrl 수정
- newslettername 중복 제거
- 변수명 수정 newsletterDto -> newsletter
- thumbnailUrl prefix 수정
<br/>
- [ATR-509](https://attractorr.atlassian.net/browse/ATR-509?atlOrigin=eyJpIjoiNDM0NGFkYTYxYzgzNDZjY2JhMWRkZjg5MGExZGIwNDYiLCJwIjoiaiJ9)
<br/>
- 
<br/>
- contentUrl 수정
- newslettername 중복 제거
- 변수명 수정 newsletterDto -> newsletter
- thumbnailUrl prefix 수정
<br/>
[ATR-509]: https://attractorr.atlassian.net/browse/ATR-509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-509] fix: 검색 결과 아티클 api 리턴 데이터 수정

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/home/service/dto/search/ArticleSearchDto.java

[[ATR-509] fix: 검색 결과 아티클 api 리턴 데이터 수정 ](https://github.com/Atractorrr/Attraction-Server/commit/ae42af080f06430ca6d4486c5d498a98d227f580)
[ATR-509]: https://attractorr.atlassian.net/browse/ATR-509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-509] fix: 검색 결과 아티클 api 리턴 데이터 수정 (#230)

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleService.java
src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java

<br/>
- [ATR-510](https://attractorr.atlassian.net/browse/ATR-510?atlOrigin=eyJpIjoiYzVlYzRhOTc1MTdlNGQxMjgxODdmYzU3NzVhZmQ0YzEiLCJwIjoiaiJ9)
<br/>
- 구독하지 않은 뉴스레터의 아티클은 표기하지 않도록 변경
- 유저 구독리스트에서 구독하고 있는 뉴스레터 참고하도록 로직 추가
- 너무 많은 데이터가 나가지 않도록 size 추가 (default size = 10)
<br/>
-
<br/>
[ATR-510]: https://attractorr.atlassian.net/browse/ATR-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-510] fix: 구독하지 않은 뉴스레터의 아티클이 보이는 현상 수정

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleService.java
src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java

[[ATR-510] fix: 구독하지 않은 뉴스레터의 아티클이 보이는 현상 수정 ](https://github.com/Atractorrr/Attraction-Server/commit/2da648d0ffd287765a293209516dbab26c4dcfbd)
[ATR-510]: https://attractorr.atlassian.net/browse/ATR-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-510] fix: 구독하지 않은 뉴스레터의 아티클이 보이는 현상 수정 (#232)

---

build.gradle
src/main/java/run/attraction/api/swagger/SwaggerConfig.java
src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
src/main/java/run/attraction/api/v1/auth/config/ApplicationConfig.java
src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
src/main/java/run/attraction/api/v1/bookmark/controller/BookmarkController.java
src/main/java/run/attraction/api/v1/home/controller/HomeController.java
src/main/java/run/attraction/api/v1/introduction/controller/IntroductionController.java
src/main/java/run/attraction/api/v1/introduction/controller/SubscriptionController.java
src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
src/main/java/run/attraction/api/v1/rank/controller/RankController.java
src/main/java/run/attraction/api/v1/statistics/controller/StatisticsController.java

- [x ] Other... Please describe: chore
<br/>
- [ATR-514](https://attractorr.atlassian.net/browse/ATR-514?atlOrigin=eyJpIjoiMGZhNDYxOGNlNjk5NGNjZmI2YmI2Y2EwZmQyZTBlNTMiLCJwIjoiaiJ9)
<br/>
- API 명세를 위한 스웨거 도입
- 아직 설정을 더 해야할 부분들이 많음  
- 에러 reponse 예제가 적용되지 않음
<br/>
-
<br/>
[ATR-514]: https://attractorr.atlassian.net/browse/ATR-514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-514] chore: API 명세를 위한 스웨거 도입

---

src/main/java/run/attraction/api/v1/auth/config/SecurityConfig.java
src/main/java/run/attraction/api/v1/auth/filter/SessionFilter.java
src/main/java/run/attraction/api/v1/user/Role.java

<br/>
- [ATR-515](https://attractorr.atlassian.net/browse/ATR-515?atlOrigin=eyJpIjoiNjlmZGE1MWNhNTZhNGJjNThiNTg0OTI3Njc2MTEwMGYiLCJwIjoiaiJ9)
<br/>
- 스웨거 시큐리티 적용
<br/>
-
<br/>
[ATR-515]: https://attractorr.atlassian.net/browse/ATR-515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: 스웨거 시큐티리 적용

---

src/main/java/run/attraction/api/swagger/SwaggerConfig.java

<br/>
-
<br/>
- 스웨거 운영서버 변경
<br/>
-
<br/>

hotfix: 스웨거 운영서버 링크 변경

---

src/main/java/run/attraction/api/swagger/SwaggerConfig.java

[hotfix: 스웨거 운영서버 링크 변경 ](https://github.com/Atractorrr/Attraction-Server/commit/d25505e22bdc4fb02fe44d338d8ae53b46e23b3c)

hotfix: 스웨거 운영서버 링크 변경 (#237)

---

src/main/java/run/attraction/api/v1/auth/config/SecurityConfig.java

<br/>
- [ATR-515](https://attractorr.atlassian.net/browse/ATR-515?atlOrigin=eyJpIjoiMDYzYmExZjk5N2ZjNDE0NTg2MjY5NjQyYzRkYzA0ODIiLCJwIjoiaiJ9)
<br/>
- swagger url 추가
<br/>
-
<br/>
[ATR-515]: https://attractorr.atlassian.net/browse/ATR-515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: 스웨거 Security 수정

---

src/main/java/run/attraction/api/v1/auth/config/SecurityConfig.java

- [chore: 스웨거 Security 수정](https://github.com/Atractorrr/Attraction-Server/commit/82836a06458e918c0ef41ea07bc373a1d6030c7a)

[ATR-515] chore: 스웨거 Security 수정 (#239)

---

src/main/java/run/attraction/api/v1/auth/session/dto/UserDetailBySession.java
src/main/java/run/attraction/api/v1/user/repository/UserRepository.java

<br/>
- [ATR-522](https://attractorr.atlassian.net/browse/ATR-522?atlOrigin=eyJpIjoiMmE4MjIyNmZhOTk2NDViZWFlMWUyZmIyYjhlN2EzY2QiLCJwIjoiaiJ9)
<br/>
- 유저의 role 추가
<br/>
-
<br/>
[ATR-522]: https://attractorr.atlassian.net/browse/ATR-522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-522] feat: 세션으로 유저 정보 조회 API 수정

---

src/main/java/run/attraction/api/v1/auth/session/dto/UserDetailBySession.java
src/main/java/run/attraction/api/v1/user/repository/UserRepository.java

[[ATR-522] feat: 세션으로 유저 정보 조회 API 수정 ](https://github.com/Atractorrr/Attraction-Server/commit/7c9b1545a1a7e62f975ab73258f4fd466f5838ac)
[ATR-522]: https://attractorr.atlassian.net/browse/ATR-522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-522] feat: 세션으로 유저 정보 조회 API 수정 (#243)

---

src/test/java/run/attraction/api/v1/introduction/repository/NewsletterRepositoryTest.java
src/test/resources/sql/data-h2.sql

<br/>
- [ATR-525](https://attractorr.atlassian.net/browse/ATR-525?atlOrigin=eyJpIjoiODdkYTRlNTFiMGNiNDVmMTk4MDEwM2VlNjUzMTk3ZTciLCJwIjoiaiJ9)
<br/>
- isAgreeAdInfoReception 추가
- isAgreePersonalInfoCollection 추가
<br/>
-
<br/>
[ATR-525]: https://attractorr.atlassian.net/browse/ATR-525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-525] test: 뉴스레터 변수 추가로 테스트 수정

---

build.gradle

<br/>
- [ATR-526](https://attractorr.atlassian.net/browse/ATR-526?atlOrigin=eyJpIjoiZDQ1MTg2ZTMyZDNjNGI5MzgzZjUwMGM3YTExZmIzNDMiLCJwIjoiaiJ9)
<br/>
- 테스트 커버리를 높이기위해 시각적으로 볼 수 있게 jacoco 도입 
<br/>
-
<br/>
[ATR-526]: https://attractorr.atlassian.net/browse/ATR-526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-526] chore: 테스트 커버리지 체크를 위한 jacoco 도입

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java

[[ATR-574] fix: 최근 받은 아티클 로직 쿼리 추가 ](https://github.com/Atractorrr/Attraction-Server/commit/6b5ca3f283bcc992e29614cd1321ab4d41fd43b4)

[ATR-574] fix: 최근 받은 아티클 로직 쿼리 추가 (#249)

---

src/main/java/run/attraction/api/v1/mypage/service/archive/newsletter/MypageNewsletterServiceImpl.java

- (이전)해당 뉴스레터가 없다면 에러 발생으로 중단
- (수정)해당 뉴스레터가 없다면 pass
<br/>
- [ATR-536](https://attractorr.atlassian.net/browse/ATR-536?atlOrigin=eyJpIjoiODQwMTEzNzc0MzRjNGY0MWJlNTY5MGE4NzZlZjVkNGQiLCJwIjoiaiJ9)
<br/>
- (이전)해당 뉴스레터가 없다면 에러 발생으로 중단
- (수정)해당 뉴스레터가 없다면 pass
<br/>
-
<br/>
[ATR-536]: https://attractorr.atlassian.net/browse/ATR-536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-536] feat: 마이페이지 뉴스레터 구독함 로직 수정

---

src/main/java/run/attraction/api/v1/mypage/service/archive/newsletter/MypageNewsletterServiceImpl.java

[[ATR-536] feat: 마이페이지 뉴스레터 구독함 로직 수정 ](https://github.com/Atractorrr/Attraction-Server/commit/ef97b2ac7e110ad0654b1484bd25200a41c6749e)
[ATR-536]: https://attractorr.atlassian.net/browse/ATR-536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-536] feat: 마이페이지 뉴스레터 구독함 로직 수정 (#251)

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java

[[ATR-541] fix: 지난 아티클중 일부가 정상적으로 정렬되지 않는 현상을 수정 ](https://github.com/Atractorrr/Attraction-Server/commit/d3250b816656c0359f0bf560a46e2607e621385e)
[ATR-541]: https://attractorr.atlassian.net/browse/ATR-541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-541] fix: 지난 아티클중 일부가 정상적으로 정렬되지 않는 현상을 수정 (#255)

---

src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java

[fix: 잘못된 적용된 prefix 수정 ](https://github.com/Atractorrr/Attraction-Server/commit/f0920f6625e9d67de875a20ad0cb6a6d694c6e40)

fix: 잘못된 적용된 prefix 수정  (#259)

---

src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/rank/ReadBoxEvent.java
src/main/java/run/attraction/api/v1/rank/service/calculator/ConsistencyRankCalculator.java

<br/>
- [ATR-542](https://attractorr.atlassian.net/browse/ATR-542?atlOrigin=eyJpIjoiOTkyOGEwMjE5ZjUzNDMwOWJjYTljZTlkMmI0NzdhNjkiLCJwIjoiaiJ9)
<br/>
- 갱신하려는 값은 같지만 modifiedAt을 갱신해야되는 경우 존재
- 그래서 ReadBoxEvent에서 Auditing 제거
- createdAt, modifiedAt 필드생성하여 따로 관리
<br/>
-
<br/>
[ATR-542]: https://attractorr.atlassian.net/browse/ATR-542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-542] feat: streak 랭킹 시스템 수정

---

.github/workflows/deploy.yml
Dockerfile
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java

<br/>
- [ATR-548](https://attractorr.atlassian.net/browse/ATR-548?atlOrigin=eyJpIjoiMzQ3N2UwZGQ5NTYwNGRiYmFmZWY5MWM5NDc5YTcxZDIiLCJwIjoiaiJ9)
<br/>
- 기존은 받는 날도 포함되었으나 이제는 제외
- 오늘 아티클을 받았으면 다음날 아티클은 1일전으로 표기된다
<br/>
-
<br/>
[ATR-548]: https://attractorr.atlassian.net/browse/ATR-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-548] : fix: 아티클 보여주는 일수 수정

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java

[[ATR-548] : fix: 아티클 보여주는 일수 수정 ](https://github.com/Atractorrr/Attraction-Server/commit/3bdd4ab2a40abd6bc5fda086275b956b6c325a7d)
[ATR-548]: https://attractorr.atlassian.net/browse/ATR-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-548] : fix: 아티클 보여주는 일수 수정 (#266)

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java

<br/>
- [ATR-556](https://attractorr.atlassian.net/browse/ATR-556?atlOrigin=eyJpIjoiZGFhNzc0ZGNiNTg1NDg4YzljYTE4ZjFiNDBhNDFkNDMiLCJwIjoiaiJ9)
<br/>
- 인스턴스변수를 메서드화해서 매번 호출 할 때마다.  date가 갱신되도록 변경
<br/>
-
<br/>
[ATR-556]: https://attractorr.atlassian.net/browse/ATR-556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-556] fix: Fix/atr 556 modify localdate

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java

[[ATR-556] fix: 아티클 보관함에서 7일보다 더 이전 아티클이 보이는 현상 수정](https://github.com/Atractorrr/Attraction-Server/commit/0cda1ccc0752fa358faa943ee36b5c1e70ad7037)
[ATR-556]: https://attractorr.atlassian.net/browse/ATR-556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-556] fix: 아티클 보관함에서 7일보다 더 이전 아티클이 보이는 현상 수정 (#268)

---

src/main/java/run/attraction/api/v1/introduction/repository/SubscriptionRepository.java
src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java

<br/>
<br/>
- 원인 : 지워지지 않은 모든 구독된 뉴스레터를 가져오도록 되어있었음
- 해당 사용자가 구독한 뉴스레터만 가져오도록 수정
<br/>
-
<br/>

fix: 마이페이지 구독한 뉴스레터가 비정상적으로 많이 출력되는 현상 수정

---

README.md

<br/>
- ATR-557
<br/>
- README.md
<br/>
-
<br/>

[ATR-557] docs: 557 README.md 작성

---

.github/workflows/pull_request.yml

fix: conflict

---

.github/workflows/pull_request.yml
README.md
src/main/java/run/attraction/api/v1/archive/dto/request/UserArticlesRequest.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/introduction/controller/SubscriptionController.java
src/main/java/run/attraction/api/v1/introduction/dto/response/SubscribedNewsletterResponse.java
src/main/java/run/attraction/api/v1/introduction/service/SubscriptionService.java

https://github.com/Atractorrr/Attraction-Server/pull/277

[ATR-583] feat: 아티클 필터 추가 - 뉴스레터

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
src/main/java/run/attraction/api/v1/bookmark/dto/BookmarkArticleRequest.java
src/main/java/run/attraction/api/v1/bookmark/service/BookmarkService.java

- 북마크 페이지에서도 아티클 보관함 처럼 뉴스레터 별로 볼 수 있도록 필터 추가
<br/>
- [ATR-578](https://attractorr.atlassian.net/browse/ATR-578?atlOrigin=eyJpIjoiMzk1YTIzZWZmMWI1NDcyZWFmM2Y1YjFmNDkyYzFhMzQiLCJwIjoiaiJ9)
<br/>
- 북마크 페이지에서도 아티클 보관함 처럼 뉴스레터 별로 볼 수 있도록 필터 추가
<br/>
-
<br/>
[ATR-578]: https://attractorr.atlassian.net/browse/ATR-578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-578] feat: 북마크페이지에서 필터 추가 - 뉴스레터

---

build.gradle
src/main/java/run/attraction/api/v1/gmail/dto/UserGmailDto.java
src/main/java/run/attraction/api/v1/gmail/event/SubscribeVo.java
src/main/java/run/attraction/api/v1/gmail/event/UserSubscribedEvent.java
src/main/java/run/attraction/api/v1/introduction/event/AutoSubscribeVo.java
src/test/java/run/attraction/api/v1/introduction/repository/NewsletterRepositoryTest.java

<br/>
- [ATR-598](https://attractorr.atlassian.net/browse/ATR-598?atlOrigin=eyJpIjoiODAyZTI5OTg4NjY5NDRjMGFiZWJkZmUyZmI4NDQ2NmMiLCJwIjoiaiJ9)
<br/>
- 사용하지 않는 jwt 패키지 삭제
- springframework.boot 3.2.5 -> 3.3.2
- io.spring.dependency-management 1.1.4 -> 1.1.6
- com.google.code.gson:gson:2.8.7 -> 2.10
- google-api-client:2.0.0 -> 2.6.0
- google-oauth-client-jetty:1.34.1 -> 1.36.0
- mariadb-java-client:2.7.2 -> spring-boot bom
- spring-kafka:3.2.0 -> spring-boot bom
<br/>
-
<br/>
[ATR-598]: https://attractorr.atlassian.net/browse/ATR-598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-598] chore: 패키지 버전 업데이트 및 삭제 

---

build.gradle
src/main/java/run/attraction/api/v1/gmail/dto/UserGmailDto.java
src/main/java/run/attraction/api/v1/gmail/event/SubscribeVo.java
src/main/java/run/attraction/api/v1/gmail/event/UserSubscribedEvent.java
src/main/java/run/attraction/api/v1/introduction/event/AutoSubscribeVo.java
src/test/java/run/attraction/api/v1/introduction/repository/NewsletterRepositoryTest.java

https://github.com/Atractorrr/Attraction-Server/pull/281

[ATR-598] chore: 패키지 버전 업데이트 및 삭제  (#281)

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java

<br/>
- [ATR-601](https://attractorr.atlassian.net/browse/ATR-601?atlOrigin=eyJpIjoiODZjYTFkMDEyNmQ1NGIxNzgwNjRmOTFiZWFjZTRhYzUiLCJwIjoiaiJ9)
<br/>
- getTotal 메서드에 일부 코드가 빠져있어서 페이지네이션에 불필요한 페이지가 더 추가 되는 현상 수정
<br/>
-
<br/>
[ATR-601]: https://attractorr.atlassian.net/browse/ATR-601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-601] fix: 페이지네이션이 정상적으로 동장하지 않는 현상 수정

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java

https://github.com/Atractorrr/Attraction-Server/pull/285

[ATR-601] fix: 페이지네이션이 정상적으로 동장하지 않는 현상 수정 (#285)

---

build.gradle
src/main/java/run/attraction/api/v1/auth/config/RedisConfig.java
src/main/java/run/attraction/api/v1/auth/filter/SessionFilter.java

<br/>
- [ATR-595]
<br/>
- 세션 Redis에 저장
<br/>
-
<br/>
[ATR-595]: https://attractorr.atlassian.net/browse/ATR-595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-595] feat: 세션 Redis 적용

---

build.gradle
src/main/java/run/attraction/api/v1/auth/config/RedisConfig.java
src/main/java/run/attraction/api/v1/auth/filter/SessionFilter.java

[[ATR-595] feat: 세션 Redis 적용 ](https://github.com/Atractorrr/Attraction-Server/commit/fce380535336f84bcc8cf29f048c73e5c61bfe93)
[ATR-595]: https://attractorr.atlassian.net/browse/ATR-595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-595] feat: 세션 Redis 적용 (#287)

---

build.gradle
src/main/java/run/attraction/api/v1/auth/config/RedisConfig.java
src/test/java/run/attraction/api/v1/bookmark/repository/BookmarkRepositoryTest.java
src/test/java/run/attraction/api/v1/bookmark/service/BookmarkServiceTest.java

feat: 세션 적용 Rollback

---

build.gradle
src/main/java/run/attraction/api/v1/auth/config/RedisConfig.java
src/test/java/run/attraction/api/v1/bookmark/repository/BookmarkRepositoryTest.java
src/test/java/run/attraction/api/v1/bookmark/service/BookmarkServiceTest.java

[feat: 세션 적용 Rollback ](https://github.com/Atractorrr/Attraction-Server/commit/c225c89dd2c14c3ac72fb524f6a1d813cbd428dc)

feat: 세션 적용 Rollback (#289)

---

src/main/java/run/attraction/api/v1/auth/config/SecurityConfig.java
src/main/java/run/attraction/api/v1/auth/config/condition/SessionFilterCondition.java
src/main/java/run/attraction/api/v1/auth/filter/SessionFilter.java

<br/>
- [ATR-609] 
<br/>
- 로컬에 API 테스트시 사용
<br/>
-
<br/>
[ATR-609]: https://attractorr.atlassian.net/browse/ATR-609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-609] feat: SessionFilter 비활성화 기능 추가

---

src/main/java/run/attraction/api/v1/auth/config/SecurityConfig.java
src/main/java/run/attraction/api/v1/auth/config/condition/SessionFilterCondition.java
src/main/java/run/attraction/api/v1/auth/filter/SessionFilter.java

[[ATR-609] feat: SessionFilter 비활성화 기능 추가 ](https://github.com/Atractorrr/Attraction-Server/commit/6398b508a453c62159a87943291437842460c16e)

[ATR-609] feat: SessionFilter 비활성화 기능 추가 (#292)

---

.github/workflows/dev.yml

<br/>
- [ATR-611](https://attractorr.atlassian.net/browse/ATR-611?atlOrigin=eyJpIjoiMzIwM2IwMmRlMDIxNGQyNzkzZmYzNDRiYWY1M2I0ZWMiLCJwIjoiaiJ9)
<br/>
- 프로덕션 서버와 github action 분리  
- ECR 대신 docker hub 사용
- 프로덕션 서버와 DB 분리
<br/>
-
<br/>
[ATR-611]: https://attractorr.atlassian.net/browse/ATR-611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-611] chore: 스테이징 서버 ci/cd 설정

---

.github/workflows/dev.yml

<br/>
- [ATR-612](https://attractorr.atlassian.net/browse/ATR-611?atlOrigin=eyJpIjoiMDk2YWQyODJlMmVjNDMxZDhkOWI0ZmMzZWNkYjcyNGYiLCJwIjoiaiJ9)
<br/>
- docker hub name 제대로 설정
<br/>
-
<br/>
[ATR-612]: https://attractorr.atlassian.net/browse/ATR-612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-612] style: 오타 수정

---

.github/workflows/dev.yml

<br/>
- [ATR-613](https://attractorr.atlassian.net/browse/ATR-613?atlOrigin=eyJpIjoiMzA2OGZhNTFiNWZiNDMwZjk5OTVhYmQ2MDI5ZGIyYWYiLCJwIjoiaiJ9)
<br/>
- 스테이징 서버에서 사용하지 않는 filebeat 실행 명령어 제거
<br/>
-
<br/>
[ATR-613]: https://attractorr.atlassian.net/browse/ATR-613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-613] chore: 스테이징 서버에서 사용하지 않는 filebeat 실행 명령어 삭제

---

.github/workflows/dev.yml
docker-compose.yml

<br/>
- [ATR-615](https://attractorr.atlassian.net/browse/ATR-615?atlOrigin=eyJpIjoiNTkzNjNlMDdmODM3NDlmZGFlMjliZWU4NjBlMzI1MzgiLCJwIjoiaiJ9)
<br/>
- [스테이징 서버] 기존 docker -> docker compose로 변경
<br/>
-
<br/>
[ATR-615]: https://attractorr.atlassian.net/browse/ATR-615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-615] chore: 스테이징 서버 배포 방식을 docker compose로 마이그레이션

---

.github/workflows/dev.yml
docker-compose.yml

<br/>
-
<br/>
- docker-compose.yml 파일 찾기지 못하여 docker-compose.yml 파일을 직접 가져오도록 설정
<br/>
-
<br/>

[ATR-615] chore: docker-compose.yml 파일 직접 가져오도록 설정

---

.github/workflows/dev.yml

<br/>
-
<br/>
- docker-compose.yml에 필요한 환경 변수 설정
- docker-compose.yml이 이미 있다면 덮어쓰도록 설정
<br/>
-
<br/>

hotfix: 환경 변수 설정

---

.github/workflows/dev.yml
docker-compose.yml

<br/>
-
<br/>
- github action 스크립트 명령어 추가 
-  docker-compose up -d
- docker-compose.yml에서 불필요한 문법 삭제
- version 스크립트 삭제 
<br/>
-
<br/>

hotfix: githubaction 스크립트 명령어 추가 및 불필요한 문법 삭제

---

src/main/java/run/attraction/api/v1/archive/dto/NewsletterDTO.java
src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/introduction/Newsletter.java
src/test/resources/sql/data-h2.sql

<br/>
- [ATR-616](https://attractorr.atlassian.net/browse/ATR-616?atlOrigin=eyJpIjoiZGI3OWUwZGJlNjUwNDg0MTg1YTY5YTZmNjg1Mjk5OTkiLCJwIjoiaiJ9)
<br/>
- newsletter에 prevArticleListUrl 추가
- newsletter에서 mainLink를 homepageUrl로 받을 수 있는 메서드 추가
- newsletterDTO에 homepageUrl, prevArticleListUrl 추가
<br/>
-
<br/>
[ATR-616]: https://attractorr.atlassian.net/browse/ATR-616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-616] feat: homepageUrl/prevArticleListUrl 필드 추가

---

src/main/java/run/attraction/api/v1/announcement/dto/PinnedPostSummaryDTO.java
src/main/java/run/attraction/api/v1/announcement/dto/PostDTO.java
src/main/java/run/attraction/api/v1/announcement/dto/PostSummaryDTO.java
src/main/java/run/attraction/api/v1/announcement/service/AnnouncementService.java

<br/>
- DTO에서 카테고리를 한글에서 영어로 전달하도록 변경
<br/>
-
<br/>

refactor: DTO에서 카테고리를 한글에서 영어로 전달하도록 변경
