src/main/java/run/attraction/api/v1/introduction/controller/IntroductionController.java
src/main/java/run/attraction/api/v1/introduction/dto/response/NewsletterResponse.java
src/main/java/run/attraction/api/v1/introduction/exception/ErrorMessages.java
src/main/java/run/attraction/api/v1/introduction/exception/GlobalExceptionHandler.java
src/main/java/run/attraction/api/v1/introduction/exception/IntroductionExceptionHandler.java
src/main/java/run/attraction/api/v1/introduction/exception/ResourceNotFoundException.java
src/main/java/run/attraction/api/v1/introduction/repository/NewsletterRepository.java
src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java
src/test/java/run/attraction/api/v1/introduction/controller/IntroductionControllerTest.java
src/test/java/run/attraction/api/v1/introduction/service/IntroductionServiceTest.java

<br/>
- ATR-63
<br/>
- 뉴스레터 get API 구현 
- 특정 뉴스레터 id를 전달해주면 사전에 정의된 정보를  return 해줌  
- 예외 처리 구현
- api를 사용하면서 발생할 수 있는 예외 처리 구현
- IntroductionController 예외
- Global 예외 
<br/>
-
<br/>

[ATR-63] 뉴스레터 get API 구현

---

build.gradle
src/main/java/run/attraction/api/v1/auth/config/AuthProviderConfig.java
src/main/java/run/attraction/api/v1/auth/controller/AuthTestController.java
src/main/java/run/attraction/api/v1/auth/provider/AuthProvider.java
src/main/java/run/attraction/api/v1/auth/provider/oauth/OAuthToken.java
src/main/java/run/attraction/api/v1/auth/token/GoogleRefreshToken.java
src/main/java/run/attraction/api/v1/auth/token/repository/GoogleRefreshTokenRepository.java
src/main/java/run/attraction/api/v1/user/User.java
src/main/resources/data.sql

<br/>
- [ATR-170](https://attractorr.atlassian.net/browse/ATR-170?atlOrigin=eyJpIjoiMDZmZDQ0YTgyOGZhNDY5NDg2OWZmYjJjZDc1MzIwZTkiLCJwIjoiaiJ9) : google refresh token 추가
<br/>
- 회원의 Gmail을 확인하기 위해 회원의 google refresh token이 필요
- google refresh token 엔티티 생성
- 구성 : email(String) , token(String), shouldReissueToken(boolean)
- shouldReissueToken는 default가 false이고 Token이 만료되면 true로 변환
- shouldReissueToken는 로그인 과정에서 google API로 부터 받으면 저장
<br/>
-
<br/>
[ATR-170]: https://attractorr.atlassian.net/browse/ATR-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-170] feat : google refresh token 추가

---

src/main/java/run/attraction/api/v1/archive/Subscribe.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java

<br/>
- [ATR-244](https://attractorr.atlassian.net/browse/ATR-244?atlOrigin=eyJpIjoiZDhlZjE1ZmQ1ZjM2NGRlNDg2YjY4OGY0ODhlMTRjN2MiLCJwIjoiaiJ9)
<br/>
- [[ATR-244] fix: subscribe entity가 제대로 초기화 되지 않는 문제 수정](https://github.com/Atractorrr/Attraction-Server/commit/31dc61d73a30b2255b6395aaadd5cd1f9cd19c67) 
- 생성자에서 newsletterIds를 초기화하지 않음
- 불필요한 생성자 만들지 않고 builder 패턴 사용
<br/>
-
<br/>
[ATR-244]: https://attractorr.atlassian.net/browse/ATR-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATR-244]: https://attractorr.atlassian.net/browse/ATR-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR - 244] fix: subscribe entity가 제대로 생성되지 않는 문제 수정

---

src/main/java/run/attraction/api/v1/archive/dto/request/UserArticlesRequest.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java

<br/>
- [ATR-260](https://attractorr.atlassian.net/browse/ATR-260?atlOrigin=eyJpIjoiYjY5ZTk1ZjEwYTRlNDlhZThiN2IzZDBkZWMyZTUwYmIiLCJwIjoiaiJ9)
<br/>
- [[ATR-260] fix: 최신순 오래된순 정렬이 서로 반대되는 현상 수정](https://github.com/Atractorrr/Attraction-Server/commit/c574dba40f46d80efb560546dc1a0af4fcb6062d)
<br/>
-
<br/>
[ATR-260]: https://attractorr.atlassian.net/browse/ATR-260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATR-260]: https://attractorr.atlassian.net/browse/ATR-260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-260] fix: 정렬이 반대로 되는 오류 수정

---

src/main/java/run/attraction/api/v1/home/service/dto/article/ArticleDetailDto.java

<br/>
- [ATR-261](https://attractorr.atlassian.net/browse/ATR-261?atlOrigin=eyJpIjoiZWYzYWEwODgxNzZiNDFiZWJkOWI5OWMwZTRiZjg3NGIiLCJwIjoiaiJ9)
<br/>
- readingTime : 해당 아티클을 읽는데 걸리는 시간
- 수정 전 : readingTime = 0 인 경우를 예외처리 했음
- 수정 후 : readingTime = 0 인 경우는 FE에서 1분미만 이라고 표시할 예정이기 때문에, 0인 경우를 예외처리하며 안됨.
- 변경 사항 : 음수인 경우에만 예외처리함.
<br/>
-
<br/>
[ATR-261]: https://attractorr.atlassian.net/browse/ATR-261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-261] fix: readingTime = 0 인 경우도 반영

---

build.gradle
src/main/java/run/attraction/api/v1/statistics/AgeGroup.java
src/main/java/run/attraction/api/v1/statistics/NewsletterEvent.java
src/main/java/run/attraction/api/v1/statistics/repository/NewsletterEventRepository.java
src/test/java/run/attraction/api/v1/statistics/AgeGroupTest.java
src/test/java/run/attraction/api/v1/statistics/NewsletterEventRepositoryTest.java
src/test/resources/data-h2.sql

<br/>
- [ATR-282](https://attractorr.atlassian.net/browse/ATR-282?atlOrigin=eyJpIjoiY2JiMWYwNDIxNzI4NDEwNzhhNDQxYTU4YjkxZTY0YmEiLCJwIjoiaiJ9)
<br/>
- `AgeGroup` 
-  테이블에서 사용자의 연령대를 표시하는 객체 
- `NewsletterEvent ` 
- 사용자가 아티클을 다 읽었을때, 해당 아티클의 뉴스레터 정볼르 저장
- 저장할때, 사용자의 연령대와 직업을 같이 저장
<br/>
-
<br/>
[ATR-282]: https://attractorr.atlassian.net/browse/ATR-282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-282] feat: 통계 테이블 생성

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/statistics/repository/NewsletterEventRepository.java

<br/>
- [ATR-412](https://attractorr.atlassian.net/browse/ATR-412?atlOrigin=eyJpIjoiNTAyMDY2ZmVmY2NlNGMzYjhjNzQzYmYxODY0ZjU4MjciLCJwIjoiaiJ9)
<br/>
- ReadBox=100 인 경우 NewsletterEvent 저장
- 해당 아티클의 뉴스레터 id와 사용자의 적업군 연령대 저장
<br/>
-
<br/>
[ATR-412]: https://attractorr.atlassian.net/browse/ATR-412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-412] feat: NewsletterEvent 저장 로직 추가

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java

- article.userEmail이 분변력이 없어졌기에 제거
- readBox.userEmail과 파라미터로 받은 userEmail로 join
<br/>
- [ATR-441](https://attractorr.atlassian.net/browse/ATR-441?atlOrigin=eyJpIjoiZDljNmJiMDRhNGZlNDg4N2E2NzEzMDhiNzMwYWZmMTEiLCJwIjoiaiJ9)
<br/>
-
<br/>
-
<br/>
[ATR-441]: https://attractorr.atlassian.net/browse/ATR-441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-441] feat: findArticleByUserEmailAndArticleId 메서드 수정

---

src/main/java/run/attraction/api/v1/introduction/Newsletter.java
src/main/java/run/attraction/api/v1/introduction/dto/response/NewsletterResponse.java

[[ATR-487] feat: 뉴스레터 엔티티에 동의 필드 추가 ](https://github.com/Atractorrr/Attraction-Server/commit/6e123fe334903e7fdc8ff69c67d54e8c47df279e)
[ATR-487]: https://attractorr.atlassian.net/browse/ATR-487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-487] feat: 뉴스레터 엔티티에 동의 필드 추가 (#220)

---

src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
src/main/java/run/attraction/api/v1/introduction/utils/SubscriptionUtil.java

- 존재하지 않는 뉴스레터 id가 구독함에 들어있는 경우 고려
- 기존 로직은 고려하고 있지 않아서 에러 발생으로 아예 메서드 중단
<br/>
- [ATR-502](https://attractorr.atlassian.net/browse/ATR-502?atlOrigin=eyJpIjoiNTMwZjQ3MmRiNDZkNDcxM2JkNjZlNzk5NjNjM2JlOTMiLCJwIjoiaiJ9)
<br/>
- 기존 로직은 존재 하지 않는 뉴스레터 id가 구독함에 들어있는 상황을 고려하고 있지 않아서 에러 발생으로 아예 메서드 중단
수정 -->  존재하지 않는 뉴스레터 id가 구독함에 들어있는 경우 고려
<br/>
-
<br/>
[ATR-502]: https://attractorr.atlassian.net/browse/ATR-502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-502] fix: 아티클 보관함 및 최근 받은 아티클 에러 수정

---

src/main/java/run/attraction/api/v1/introduction/service/SubscriptionService.java

[[ATR-503] feat: 자동 구독이 가능할 때만 카프카메시지 전송해서 동작하도록 수정 ](https://github.com/Atractorrr/Attraction-Server/commit/77decee05f75fe878f014784bc301b7445b05d21)
[ATR-503]: https://attractorr.atlassian.net/browse/ATR-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-503] feat: 자동 구독이 가능할 때만 카프카메시지 전송해서 동작하도록 수정 (#228)

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java

- 최근 받은 아티클중에 아티클을 받은지 7일 이내만 보여주도록 설정 추가
- .where(article.receivedAt.between(sixDaysAgo, currentDate)) 추가
<br/>
- [ATR-534](https://attractorr.atlassian.net/browse/ATR-534?atlOrigin=eyJpIjoiN2JjYWJkY2MxNjkzNDgxMTk0NzFlMjMzYjNiZjhiOWMiLCJwIjoiaiJ9)
<br/>
- 최근 받은 아티클중에 아티클을 받은지 7일 이내만 보여주도록 설정 추가
- .where(article.receivedAt.between(sixDaysAgo, currentDate)) 추가
<br/>
현재 받은지 7일 넘어가는 아티클도 보임
```java
.where(readBox.modifiedAt.isNotNull()
.and(Expressions.dateTemplate(LocalDate.class, "DATE({0})", readBox.modifiedAt)
.between(sixDaysAgo, currentDate))
```
해당 로직으로는  읽은 것을 또 읽으면 modifiedAt이 업데이트 되기 때문에 7일이내 계속 아티클을 본다면 데이터가 아예 삭제될 때 까지 읽은 아티클에서 볼 수 있음
<br/>
[ATR-534]: https://attractorr.atlassian.net/browse/ATR-534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …

[ATR-534] hotfix: 최근 받은 아티클 로직 쿼리 추가

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java

<br/>
- [ATR-541](https://attractorr.atlassian.net/browse/ATR-541?atlOrigin=eyJpIjoiOGMxYThjNzE5ODUzNGQ3YTljZDEwOTc1Nzg4ZGFhN2QiLCJwIjoiaiJ9)
<br/>
- 지난 아티클중 일부가 정상적으로 정렬되지 않는 현상 수정
- DESC 정렬
- [refactor: limit를 서비스단에서 레포에서 사용하도록 변경](https://github.com/Atractorrr/Attraction-Server/pull/253/commits/815591f89f4e3b944108e8dec03886ad5b8e526c)
<br/>
-
<br/>
[ATR-541]: https://attractorr.atlassian.net/browse/ATR-541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-541] fix: 지난 아티클중 일부가 정상적으로 정렬되지 않는 현상을 수정

---

src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java

[[ATR-541] fix: 지난 아티클중 일부가 정상적으로 정렬되지 않는 현상을 수정 ](https://github.com/Atractorrr/Attraction-Server/commit/e91d3d4ce27459939191ee29797b61596185d876)
[ATR-541]: https://attractorr.atlassian.net/browse/ATR-541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-541] fix: 지난 아티클중 일부가 정상적으로 정렬되지 않는 현상을 수정 (#253)

---

.github/workflows/deploy.yml
Dockerfile

<br/>
- [ATR-548](https://attractorr.atlassian.net/browse/ATR-548?atlOrigin=eyJpIjoiYjBkYWNjNWIzOWU3NGNkYWJkMDY2OGZiNzJjYzJlNDMiLCJwIjoiaiJ9)
<br/>
- 도커 타임존 서울로 설정
<br/>
현재 서버는 로컬타임이 서울로 설정 되어있지만 도커 내부는  UTC로 설정되어있음
<br/>
[ATR-548]: https://attractorr.atlassian.net/browse/ATR-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-548] fix: 도커 타임존 서울로 설정

---

.github/workflows/deploy.yml
Dockerfile

[[ATR-548] chore: docker 타임존 서울로 설정 ](https://github.com/Atractorrr/Attraction-Server/commit/83c2ccbdb1458337f78c7c3f974266bc0c28a92b)
[ATR-548]: https://attractorr.atlassian.net/browse/ATR-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-548] chore: docker 타임존 서울로 설정 (#264)

---

src/main/java/run/attraction/api/v1/introduction/service/SubscriptionService.java

- 구독은 취소한 뉴스레터는 가져오지 않도록 수정
<br/>
- [ATR-599](https://attractorr.atlassian.net/browse/ATR-599?atlOrigin=eyJpIjoiOGQyNDIzNjk2OTYyNGE5NTk2NWU3MDU2NGU0YzFlM2MiLCJwIjoiaiJ9)
<br/>
- 구독 취소한 뉴스레터는 가져오지 않도록 수정
<br/>
-
<br/>
[ATR-599]: https://attractorr.atlassian.net/browse/ATR-599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATR-599] fix: 구독한 뉴스레터를 가져올 때 구독취소한 것도 가져오는 현상 수정

---

src/main/java/run/attraction/api/v1/announcement/controller/AnnouncementController.java
src/main/java/run/attraction/api/v1/announcement/repository/AnnouncementRepository.java
src/main/java/run/attraction/api/v1/announcement/service/AnnouncementService.java

<br/>
- 기존 
- 고정글 무제한으로 가능
- 변경
- 고정글 3개로 제한  
<br/>
-
<br/>

fix: 공지사항에서 고정글을 3개로 제한하도록 변경

---

src/main/java/run/attraction/api/v1/announcement/PostCategory.java
src/main/java/run/attraction/api/v1/announcement/controller/AnnouncementController.java
src/main/java/run/attraction/api/v1/announcement/dto/CustomPageDTO.java
src/main/java/run/attraction/api/v1/announcement/repository/AnnouncementRepository.java
src/main/java/run/attraction/api/v1/announcement/service/AnnouncementService.java

<br/>
- 카테고리로도 게시물을 가져올 수 있도록 기능 추가
- 고정되지 않은 모든 게시물을 가져올 때 파라미터로 카테고리도 받을 수 있도록 추가 
- 응답에 파라미터에 카테고리를 넣으면  표기 넣지 않으면 null로 표기
<br/>
-
<br/>

feat: 카테고리로도 게시물을 가져올 수 있도록 기능 추가

---

src/main/java/run/attraction/api/v1/announcement/controller/AnnouncementController.java
src/main/java/run/attraction/api/v1/announcement/dto/CustomPageDTO.java
src/main/java/run/attraction/api/v1/announcement/dto/OneBasedPage.java
src/main/java/run/attraction/api/v1/announcement/dto/request/PostSearchRequest.java

<br/>
- 페이지가 1부터 시작하도록 보정
- 기존 0부터 시작
<br/>
-
<br/>

refactor: 페이지가 1부터 시작하도록 보정
